### ISSUE TITLE
 Images Popups Not Working

### ISSUE THREAD

**Issue by princedm** [archetyped/simple-lightbox#1000]
I am writing to report an issue that has suddenly stopped working on my site. Specifically, when I click on an image, it no longer displays a popup on any posts. I have attempted to troubleshoot the issue by disabling the Cache plugin, but the problem persists.

I kindly request that you investigate the matter and provide a solution. If there is anything I can do to assist with the resolution, please let me know.

The page I need help with: [https://www.taknikigyan.in/windows-original-product-key-kaise-pata-kare/
](https://www.taknikigyan.in/windows-original-product-key-kaise-pata-kare/)

I have checked on all browsers and Incognito windows as well such as Firefox, Chrome, Opera

## Details

* URL of Page exhibiting problem: https://www.taknikigyan.in/windows-original-product-key-kaise-pata-kare/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chrome, Opera
* Version of SLB Installed: Version 2.9.3 
* Other plugins installed: Ad Inserter, AddToAny Share Buttons, Akismet Anti-Spam, Astra Widgets, Block Navigation, Broken Link Checker, Code Snippets, Easy Table of Contents, Ezoic, FileBird Lite, Formidable Forms, Gutentor - Gutenberg Blocks - Page Builder for Gutenberg Editor, Health Check & Troubleshooting, Internal Link Juicer, Internal Links Manager, Kadence Blocks – Gutenberg Blocks for Page Builder Features, LiteSpeed Cache, Rank Math SEO, Schema & Structured Data for WP & AM, Simple Author Box, Spectra, Sucuri Security - Auditing, Malware Scanner and Hardening, Temporary Login Without Password, ThirstyAffiliates, UpdraftPlus - Backup/Restore, WordPress Popular Posts, WPCode Lite, YellowPencil

**Comment by archetyped** [comment]
Hi, the link provided appears to have multiple 404 errors when loading external CSS and JS files.  Many of these errors appear to be related to the "lightspeed" plugin.  This appears to be preventing SLB's code from loading.

Following [these instructions for identifying plugin/theme conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts) is recommended to determine the specific plugin preventing SLB's code from loading.  Once the conflicting plugin(s) is disabled, SLB should work as expected once again.

Please provide the name and URL of any conflicting plugins you have identified, so that I can determine whether anything can be done from SLB's side.  Reporting the issue to the developers of the conflicting plugin is also recommended.

Please provide an updated URL if you are still experiencing an issue after removing the conflicting plugin(s) and I would be glad to reopen this ticket and take another look.

Thanks.

**Comment by archetyped** [comment]
Hi, SLB does not appear to be installed or activated at the link provided.  Please ensure that SLB is installed and activated when testing your site.  If you are still experiencing an issue, please provide an updated link and a screenshot of SLB's admin settings page.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take another look.
