### ISSUE TITLE
Working on some computers and not on others

### ISSUE THREAD

**Issue by underlyne12** [archetyped/simple-lightbox#1001]
## Description

When working with Lightbox, I am able to use it and see it working on my computer but when I look on another computer/device, it is not opening and opens the images directly to their WP content url.

## Details

* URL of Page exhibiting problem: https://bainwaveproperty.com.au/gallery/
* Chrome, Safari
* 2.9.3 
* Other plugins installed: SiteGround Central
SiteGround Optimizer
SiteGround Security
W3 Total Cache
WordPress Importer
WPForms Lite

**Comment by underlyne12** [comment]
I have reactivated the plugin. For this page, just for the first gallery
section, Kitchen transformations.

https://bainwaveproperty.com.au/gallery/

Thanks,
Ellen

**Comment by archetyped** [comment]
Hi, it appears the page has a gallery generated by the NextGEN Gallery plugin.  In order to use SLB with that gallery, you will need to disable the plugin's own built-in lightbox functionality, then activate and enable SLB.

Please also note that some plugins have started to include something called "Simple Lightbox".  However, that is a different lightbox that unfortunately chose to use the same name as this plugin.  The [actual Simple Lightbox plugin in WordPress' plugin directory](https://wordpress.org/plugins/simple-lightbox/) is purpose-built for WordPress.

Please provide an updated link and a screenshot of SLB's admin settings page if you are still experiencing an issue after following the above instructions and ensuring that SLB is activated and enabled, and I would be glad to take another look.

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
