### ISSUE TITLE
Making Simple Lightbox Work

### ISSUE THREAD

**Issue by CyberWrek** [archetyped/simple-lightbox#1005]
## Description of Problem

Hi,

Total noob question. I've been piecing together a WordPress website and wanted to add a little more functionality to it. Figured Simple Lightbox would add a little flair to thumbnail images, but I have NO clue how to make it work inside an item.

Here's the page I'm working on: https://rcpg.connectrax.com/guidelines/a2/

The image on the right currently opens to its own page, but I'd like it to open in a lightbox. I don't want every image on the site to do this, so I'm hoping this is a page-specific plugin. Any help would be appreciated.

Thanks!

## Details

* URL of Page exhibiting problem: https://rcpg.connectrax.com/guidelines/a2/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed: 
* Active theme (name & link): 
* Screenshot of SLB's options page:

**Comment by CyberWrek** [comment]
Hi @archetyped,

Unfortunately, I am clueless with this. Normally with other plugins, I get a solid sense of what to do. With SLB, it's activated and enabled, but I can't get the lightbox to appear when I click on my images. I also don't want every image to open in a lightbox, only selected ones. Any specific guidance would be greatly appreciated.

Thanks!

**Comment by archetyped** [comment]
> I also don't want every image to open in a lightbox, only selected ones.

The first item of the **Features** list on [SLB's page in WordPress' Plugin Directory](https://wordpress.org/plugins/simple-lightbox/) notes:

**Automatically activate links (no manual coding required)**

In other words, SLB is designed to automatically display all valid links in the lightbox when clicked by default without any further steps required.

There are ways to [exclude specific links](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes#slb_exclude) from being displayed in the lightbox, but if you want to manually select specific links to be shown in the lightbox, SLB probably isn't the right plugin for your needs.

If so, feel free to close this ticket.  If you would still like to get SLB working on your site, please provide more detail on where you're running into issues on providing the previously-requested details so that your issue can be fully evaluated.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
