### ISSUE TITLE
Simple box not working multisitewise

### ISSUE THREAD

**Issue by rggrggrgg** [archetyped/simple-lightbox#1023]
## Description of Problem

I don't understand why my installation of wordpress multisite does not support Simple LightBox Plugin 
## Details

* URL of Page exhibiting problem: https://consulenzegioviali.it
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): anyone
* Version of SLB Installed: latest
* Other plugins installed: even with no plugin activated, it just doesn't work.  An image opens in empty window instead.  This happens even with standard themes.  The server host says it is a bad Wordpress configuration, but I have no idea how to correct this.

**Comment by archetyped** [comment]
Hi, there do not appear to be any valid image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

Please provide a link to a specific page (i.e. not just the site's home page) that exhibits the issue you are experiencing.

Please also note that "latest" is not a valid SLB version.  Please edit your original post to include the necessary details so that your issue can be fully evaluated.

**Comment by rggrggrgg** [comment]
Please visit new blank installation:
HTTPS://centralfixation.com

**Comment by archetyped** [comment]
Hi, it looks like the only image link at the page provided is added via WordPress' FSE template editor.

SLB supports image links in native content areas such as posts/pages, widgets, menus, etc.

Support for FSE template blocks is planned for a future update ([details](#1010)).

Please let me know if you are experiencing an additional issues and I would be glad to reopen this ticket and take another look.
