### ISSUE TITLE
Lightbox not working for us noobs :)

### ISSUE THREAD

**Issue by kramerdesign-100** [archetyped/simple-lightbox#1035]
## Lightbox not working on text links

I've installed Simple Lightbox and created 2 text links to image files in media library that we'd like to open in lightbox. The links are going directly to the attachment page. We have tested with Twenty Twenty-One theme and no plugins active. This looks like simple plug and play - are we missing something?

(Update) **Location of text links in question:** https://capture.dropbox.com/FwUv0u8nocpoWeWz

## Details

* URL of Page exhibiting problem: https://rubenstein.staging.mysites.io/claims-rate/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 2.9.3
* Other plugins installed: https://capture.dropbox.com/70qYfXNIyzYBoT38

**Comment by archetyped** [comment]
Hi, the site appears to be using HTTP authentication to require a login in order to access the site.  HTTP authentication can block the loading of files and prevent SLB from functioning properly.

Removing the HTTP authentication should allow SLB to function normally.

See more details in [SLB's Requirements documentation](https://github.com/archetyped/simple-lightbox/wiki/Requirements#http-authentication).

Please let me know if you are still experiencing an issue after removing the HTTP authentication, and I would be glad to reopen this ticket and take another look.

**Comment by kramerdesign-100** [comment]
My bad! I sent you the staging link where we were testing theme and plugin conflicts. this is the actual URL of the page:
https://billrubenstein.com/claims-rate/

**Comment by kramerdesign-100** [comment]
Hi! Please disregard above – client has decided not to link images on this page and the text has been edited. Thank you just the same!

**Comment by kramerdesign-100** [comment]
Ok - sorry for the start and stop. I would like to troubleshoot this for the future. Below is a page with a text link to an image. The image opens in its attachment page rather than a lightbox. Pleae advise.
https://billrubenstein.com/lightbox-test/

**Comment by archetyped** [comment]
Your site is loading multiple versions of jQuery, including a very old version.  Loading multiple versions of jQuery prevents code from functioning properly.

SLB supports the version jQuery officially included with and supported by WordPress.  Removing the outdated version of jQuery is recommended.

See here for more information: [jQuery Support](https://github.com/archetyped/simple-lightbox/wiki/jQuery-Support)
