### ISSUE TITLE
Stopped working and just opens full path on browser

### ISSUE THREAD

**Issue by saschabrockel** [archetyped/simple-lightbox#1047]
## Description of Problem

It stopped working and is just opening the image as full path in the browser. I got the feeling that it has to do with the `WP Hide & Security` plugin. Maybe the rewrite of the wp-content folder?

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 2.9.3
* Other plugins installed: many but I guess `WP Hide & Security` is the problem

**Comment by archetyped** [comment]
Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by saschabrockel** [comment]
@archetyped https://sascha-brockel.de/msi-mainboard-wake-on-lan-einrichten/ or also the English version. Doesn't matter. It has something to do with WP Hide. That's the only thing I know. But I couldn't figure out the reason yet.

**Comment by archetyped** [comment]
Thank you for the link.

The specific issue at the link provided is most likely due to a cURL configuration issue.  See [SLB's Requirements documentation](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support) for more details.

If you recently changed hosting providers, you may need to contact the new provider to request that the cURL configuration on their end be updated.

If you did not move to a different hosting provider and SLB was previously working, then your provider may have recently made changes that affected the cURL configuration.  Contacting the provider to inquire about changes to cURL configuration is recommended.

In either case, directing your hosting provider to the aforementioned link may help them resolve the issue more quickly.

---

Though unlikely in this case, if you suspect a plugin conflict, you can [follow these steps to identify plugin/theme conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).

If you find a conflicting plugin/theme, please provide a link to the specific plugin/theme and I would be glad to take a look and see if anything can be done from SLB's end.

---

This ticket is being closed as the issue appears to be caused by an external factor.  Please update this ticket with any additional details regarding plugin conflicts, etc., and I would be glad to reopen this ticket and take another look.

**Comment by saschabrockel** [comment]
As I told you it's clearly in correlation with the WP Hide & Security plugin. As soon as it's deactivated it works again. And I tried so many things now and know what the problem is and it has to be in this plugin. I guess there will be a line of code where `wp-content` is hardcoded and that breaks things. If I start rewriting this slug it's going to break. You can test it yourself.

As soon as I deactivate this rewrite again it works.

**Comment by archetyped** [comment]
Hi, as previously-requested, please provide a **link** to the specific plugin you are experiencing a problem with to ensure that the same plugin is tested.

Please also provide screenshots of SLB's and the other plugin's settings to ensure that testing is performed with the same configuration.

Also, as you mention "If I start rewriting this slug it's going to break" and "If I change the path of `/wp-content/plugins`" it breaks too", please provide details on how you are going about changing these paths so that it can be tested.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
