### ISSUE TITLE
Not working with Blocksy Theme?

### ISSUE THREAD

**Issue by kilroy59** [archetyped/simple-lightbox#1048]
## Description of Problem

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: https://staging2.elcchamber.org/photo-gallery/
* Protected Folder Credentials
UN: elc PW: elcchamber

* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  Brave
* Version of SLB Installed:   2.9.3
* Other plugins installed: This is on a staging site, while there's several plugins installed, the only difference between it and a site where it works fine is the Theme and payment processor for Gravity Forms. (The troubled site uses Square versus PayPal.

**Comment by archetyped** [comment]
Hi, the issue is likely due to the HTTP authentication set for the site, which can prevent WordPress from loading all of the files required for plugins, themes, etc.  See [SLB's Requirements documentation](https://github.com/archetyped/simple-lightbox/wiki/Requirements#http-authentication) for more details.

Please provide an updated link if you are still experiencing an issue after HTTP authentication has been removed (be sure to fully clear your site and browser cache before testing) and I would be glad to reopen this ticket and take another look.

Also please note that the posting login details in a public forum is not recommended.  Changing your login details is recommended.
