### ISSUE TITLE
images not appearing

### ISSUE THREAD

**Issue by LisaArtist** [archetyped/simple-lightbox#1082]
## Description of Problem
I built my wordpress site with simple lightbox several years ago. I've probably ignored it for the last 18 months, and today discovered none of my galleries are displaying.

I tried viewing in both Safari and Chrome, but nothing. The URL is Lisayoungdahlart.com
My version of SLB is 2.9.3

I am attaching a screen shot to view my other plugins

I need this explained in simple terms. I am not a programmer, and my knowledge is just enough to build very basic websites.

![Screen Shot 2024-08-30 at 3 30 04 PM](https://github.com/user-attachments/assets/1fe595d7-2b53-4663-a93a-96dfcf5ba0a5)

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by LisaArtist** [comment]
I don't see the gallery images. There are 5 gallery pages. This is one of them: https://www.youngdahldesign.com/illustration/music/

I have tried to view on Chrome and Safari browsers. I am on a mac.

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links at the URL you provided.

Please provide an updated URL that contains image links and exhibits the issue you are experiencing and I would be glad to take another look.

**Comment by LisaArtist** [comment]
Per the instructions when I created the website, I created a lightbox gallery for each category in my galleries. A short code name was generated for each gallery category. I am attaching the screen shots of these, and my edit page for https://www.youngdahldesign.com/illustration/music/   This page shows where the code for the gallery has been added.

The edit Lightbox Gallery page covers 2 screen shots. I discovered today in checking this edit function that my images had disappeared from the gallery. I did not remove them. I just added one image today as a test and it is appearing on the page. Before I continue and rebuild the page, what happened to my images? Is there something I can do to prevent this happening again?

![Screen Shot 2024-09-09 at 2 45 27 PM](https://github.com/user-attachments/assets/ce27a2ab-2ac3-4558-a98d-deee8e66d250)
![Screen Shot 2024-09-09 at 2 50 16 PM](https://github.com/user-attachments/assets/3368221b-b0f6-4675-99df-25dd0a0556cd)
![Screen Shot 2024-09-09 at 2 51 05 PM](https://github.com/user-attachments/assets/5124a211-b7e4-4f74-95df-882edcd5fa0c)
![Screen Shot 2024-09-09 at 2 51 38 PM](https://github.com/user-attachments/assets/e0bbbede-a1f2-413a-910d-b90c6605f075)
![Screen Shot 2024-09-09 at 2 52 25 PM](https://github.com/user-attachments/assets/78428119-1d38-45e2-9553-88e21cff0371)

**Comment by archetyped** [comment]
> Before I continue and rebuild the page, what happened to my images? Is there something I can do to prevent this happening again?

All of your screenshots of gallery settings appear to be from a different plugin (not Simple Lightbox), so I cannot say what what happened or what can be done to prevent it from happening again.  **Simple Lightbox** works with [WordPress' native galleries](https://wordpress.org/documentation/article/gallery-block/) and does not have any gallery-specific settings itself.

If you are using a separate plugin to build your galleries, contacting the developer of that plugin is recommended.  Based on the plugin list screenshot from your first post, the [Lightbox Slider](https://wordpress.org/plugins/simple-lightbox-gallery/) appears to the gallery plugin you are referring to.  Despite the similar text in that plugin's header image, it is not related to Simple Lightbox.

In fact, since it advertises lightbox functionality itself, the other plugin may actually conflict with Simple Lightbox's own lightbox functionality.  Generally, using multiple plugins that provide the same functionality is not recommended for this reason.

If you ultimately need to rebuild your galleries from scratch, you may want to evaluate [WordPress' built-in gallery functionality](https://wordpress.org/documentation/article/gallery-block/), as you can set up the galleries directly in the post/page rather than having to build the galleries in a different section and then copy a code into a post/page.  The other benefit is that WordPress' native galleries are automatically supported by Simple Lightbox.

As the issue appears to be due to a different plugin, this ticket is being marked as "closed".  However, if you are experiencing an issue with Simple Lightbox where the other plugin is not being used, please provide an updated link to a page the exhibits the issue and I would be glad to reopen this ticket and take another look.
