### ISSUE TITLE
How to display "group_status" as a row of dots?

### ISSUE THREAD

**Issue by rubymused** [archetyped/simple-lightbox#1084]
I've read all the doc I can find, and I'm likely missing something...but can't figure out how to display the "group_status" as a row of dots with the current one "active".

I changed the format of group_status to "%current%:%total%" in the hopes that I could grab that and programmatically manipulate it in the template, but not sure how to go about that. Are we using twig here, or is this a homegrown syntax?

**Comment by archetyped** [comment]
See [SLB's Themes documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for full details on lightbox themes.

Specifically, the tutorial on [Customizing Theme Layouts](http://archetyped.com/know/slb-theme-layout/) may be helpful, with the first section titled "**It’s Just HTML**".  As such, there is no programmatic functionality in the theme layouts themselves.

Template tags are programmatically rendered, so that is likely the best place to affect a tag's output.  The public API for template tags is not finalized, but in the meantime, you can [check out the code for SLB's built-in template tags](https://github.com/archetyped/simple-lightbox/blob/master/template-tags/ui/js/dev/tag.ui.js).

**Comment by rubymused** [comment]
Thanks for the quick reply, and the pointer to the code that generates the tag output. I can make it work from there.


On Sep 17, 2024, at 1:26 PM, Archetyped ***@***.***> wrote:


See SLB's Themes documentation <https://github.com/archetyped/simple-lightbox/wiki/Themes> for full details on lightbox themes.

Specifically, the tutorial on Customizing Theme Layouts <http://archetyped.com/know/slb-theme-layout/> may be helpful, with the first section titled "It’s Just HTML". As such, there is no programmatic functionality in the theme layouts themselves.

Template tags are programmatically rendered, so that is likely the best place to affect a tag's output. The public API for template tags is not finalized, but in the meantime, you can check out the code for SLB's built-in template tags <https://github.com/archetyped/simple-lightbox/blob/master/template-tags/ui/js/dev/tag.ui.js>.
