### ISSUE TITLE
Create more than one group on a page

### ISSUE THREAD

**Issue by wwwolf3** [archetyped/simple-lightbox#148]
Summary:
I have several clusters of images on one page, and would like each cluster to be a different 'group' and have its own slideshow, rather than all the images on the page forming one big group. Can this be done?

Detail:
Page shows several holiday cottages, each with 6 images. When you click on one image, I would like to show the first as 1 of 6 and be able to click/slideshow thru the 6 images for that cottage. At the moment clicking on an image shows the correct full size image in the lightbox and numbers it correctly, but within the whole page, e.g. image 1 for cottage 2 comes up as 7 of [n].

I notice that SLB is adding, for example, data-slb-group="10" to the a tag for all images on the page, so I guess I'm looking for how to reset that for each new group, or manually attribute it to each image.

Thanks!

**Comment by annstimmel** [comment]
I can start a new thread if it's more appropriate, but since my question is related, I thought I'd start here. I'm using SLB 2.3 and am trying to take advantage of the new grouping feature. I have created multiple groups. each with its own id, on the same page, each displaying only the first image (additional images in the group open when the visible one is clicked). Everything works as expected, except when the user gets to the last image in a group, the lightbox stays open and displays the first image in the next group. I would expect it to either cycle back to the first image in the group or close the lightbox entirely. Here's a link to the page on my site http://www.darkermarkerproductions.com/entertainment/ and my code (sorry if I'm not quoting correctly!):

<h4 style="text-align: center;">Section 1</h4>

[[slb_group id="group1"]

[caption id="attachment_917" align="aligncenter" width="246"]
<a href="http://www.darkermarkerproductions.com/entertainment/img_6645/" rel="attachment class="wp-image-917 size-medium" wp-att-944"><img src="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6645.jpg" alt="IMG_6645" width="1871" height="2196" class="aligncenter size-full wp-image-944" />
</a> Click the photo to see additional images[/caption]

<div style="display: none;">

<a href="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6646.jpg" title="image2"></a>
<a href="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6638.jpg" title="image3"></a>
<a href="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6636.jpg"  title="image4"></a>
<a href="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6593.jpg"  title="image5"></a>
<a href="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6648.jpg"  title="image6"></a>

</div>
[/slb_group]]

<h4 style="text-align: center;">Section 2</h4>
[[slb_group id=”group2”]

[caption id="attachment_917" align="aligncenter" width="246"]<a href="http://www.darkermarkerproductions.com/entertainment/1656052_10105307025220850_6162249938431244709_n/" rel="attachment wp-att-917"><img class="wp-image-917 size-medium" src="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/1656052_10105307025220850_6162249938431244709_n-246x300.jpg" alt="1656052_10105307025220850_6162249938431244709_n" width="246" height="300" /></a> Click the photo to see additional images[/caption]

[/slb_group]]

**Comment by annstimmel** [comment]
I can start a new thread if it's more appropriate, but since my question is related, I thought I'd start here. I'm using SLB 2.3 and am trying to take advantage of the new grouping feature. I have created multiple groups. each with its own id, on the same page, each displaying only the first image (additional images in the group open when the visible one is clicked). Everything works as expected, except when the user gets to the last image in a group, the lightbox stays open and displays the first image in the next group. I would expect it to either cycle back to the first image in the group or close the lightbox entirely. Here's a link to the page on my site http://www.darkermarkerproductions.com/entertainment/ and my code:

    <h4 style="text-align: center;">Section 1</h4>
    
    [[slb_group id="group1"]
    
    [caption id="attachment_917" align="aligncenter" width="246"]
    <a href="http://www.darkermarkerproductions.com/entertainment/img_6645/" rel="attachment class="wp-image-917 size-medium" wp-att-944"><img src="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6645.jpg" alt="IMG_6645" width="1871" height="2196" class="aligncenter size-full wp-image-944" />
    </a> Click the photo to see additional images[/caption]
    
    <div style="display: none;">
    
    <a href="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6646.jpg" title="image2"></a>
    <a href="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6638.jpg" title="image3"></a>
    <a href="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6636.jpg"  title="image4"></a>
    <a href="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6593.jpg"  title="image5"></a>
    <a href="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/IMG_6648.jpg"  title="image6"></a>
    
    </div>
    [/slb_group]]
    
    <h4 style="text-align: center;">Section 2</h4>
    [[slb_group id=”group2”]
    
    [caption id="attachment_917" align="aligncenter" width="246"]<a href="http://www.darkermarkerproductions.com/entertainment/1656052_10105307025220850_6162249938431244709_n/" rel="attachment wp-att-917"><img class="wp-image-917 size-medium" src="http://www.darkermarkerproductions.com/wp-content/uploads/2014/12/1656052_10105307025220850_6162249938431244709_n-246x300.jpg" alt="1656052_10105307025220850_6162249938431244709_n" width="246" height="300" /></a> Click the photo to see additional images[/caption]
    
    [/slb_group]]

**Comment by archetyped** [comment]
Hi, it appears that your code is using double braces for the shortcodes (e.g. `[[slb_group id="group1"]`), but they should be single braces (e.g. `[slb_group id="group1"]`).  The double braces may be confusing WordPress' shortcode processing.

Also, you don't need to include a group ID in the shortcode if all grouped links are wrapped in the same block.
