### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by robertomarassi** [archetyped/simple-lightbox#358]
## Description of Problem
plugin doesn't work only on galleries created on pages by Munch theme (version 1.0.4). It works on any other post / page.

## Details

* URL of Page exhibiting problem: http://www.ristorantealvalentino.it/galleria/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All
* Version of SLB Installed: 2.3.1
* Other plugins installed: 
* Theme: Munch (1.0.4) (http://themeforest.net/item/munch-restaurant-business-wordpress-theme/8348506)

**Comment by archetyped** [comment]
Hi, it appears that the theme may not be using WordPress' official template tags such as `the_content()` (standard in any professional theme) for the gallery templates.  Unfortunately, as a paid theme, I am unable to take a closer look.

I would recommend contacting the theme's developers and request that they use standard template tags so that SLB can activate the images.  See here for more information on [SLB's minimum requirements](../wiki/Requirements).
