### ISSUE TITLE
More accurate description in label

### ISSUE THREAD

**Issue by dev-xiligroup** [archetyped/simple-lightbox#378]
## Description of feature/request

Be able to differentiate description when two attachments have the same image but not same title, label and description...

Can you make priority with post->ID of attachment (and not URI) - in id= or class= to search and get description (post_content)
`
[caption id="attachment_5684" align="aligncenter" width="300"]<a href="http://xxxxxxx.com/wp-content/uploads/2015/05/image-1432056336565.jpg"><img class="size-medium wp-image-5684"
`
## This feature would be used to

improve compatibility with multilingual context (here xili-language plugin)

In my plugin, to avoid media duplication, It is possible to create more than one attachment (one for each language) with the same media (image, sound). Simple lightbox works well with title and caption but not with description (post content) - the first available is detected and not the description attached to the displayed image... so an english description is shown with a good french title :-(

I examine (after source search), the file controller.php... but it is difficult to detect what to modify...

**Comment by archetyped** [comment]
Hi, SLB uses WP's own functions to determine an attachment's content, so it looks like using the same media for multiple attachments is not officially supported in WP.

Because different plugins handle multilingual functionality differently, support will be provided via add-ons for SLB.  You can leave a comment for the multilingual plugin you would like to be supported to [this ticket](205).

Thanks.

**Comment by dev-xiligroup** [comment]
As suggested, for xili-language multilingual plugin ( https://wordpress.org/plugins/xili-language/ ) using taxonomies since 6 years, the best way to use the id of attachment detected in id (or class) of displayed image. With this id, it is the more robust way to get all infos as the description.
