### ISSUE TITLE
Doesn't load on 'front-page.php' template

### ISSUE THREAD

**Issue by phylaxis** [archetyped/simple-lightbox#424]
I can't seem to get the code to load if using a `front-page.php` file in my theme. I check for any plug-in conflicts and confirmed that when I added a `front-page.php` to the Twentyfifteen theme that the code did not initialize. It seems like the `lib.core.js` and `lib.view.js` files are simply not loading if I'm using a `front-page.php` file. I have both the `Enable on Home Page` and `Enable on Pages` option checked.

**Comment by phylaxis** [comment]
OK. Looks like I solved my own issue and it wasn't the `front-page.php` template. I was calling a second loop to display the 5 most recent blog posts on my front page. Inside my `WP_Query` loop I was calling this to display the content:

```
// Display the Post
printf( '%s', get_the_content() );
```

What I needed to add was a call around that to `apply_filters`. Once I changed the code to this everything worked as expected:

```
// Display the Post
printf( '%s', apply_filters( 'the_content', get_the_content() ) );
```

I'm posting this here in case others make the same mistake.

**Comment by archetyped** [comment]
Hi, glad to hear you were able to resolve your issue.  You can also use `slb_activate()` if you just want to activate SLB for the content rather than running every function hooked into the `the_content` filter.

Here is [more information on using `slb_activate()`](http://archetyped.com/lab/slb-2-3-0/ "more information on using `slb_activate()`").

Also, if you're using `get_the_content()` and running it through the `the_content` filter, you're essentially doing the same thing as `the_content()`, so it may be simpler to use that function directly.  This will also allow SLB to automatically activate the content.`
