### ISSUE TITLE
Thumbnails not displayed

### ISSUE THREAD

**Issue by renpub** [archetyped/simple-lightbox#444]
I am running the latest version of SLB with jQuery version 2.1.4. I have set a thumbnail image size of 240 x 95 (but any size fails) and I have tried regenerating thumbnails but this page refuses to display the thumbnail image (2/3 of the way down the page in the same column where the YouTube video is embedded.
http://www.adducation.info/current-general-knowledge/list-of-mnemonics/
(Update: I had to revert to jQuery 1.8.2 so the jQuery table sorting works)

**Comment by archetyped** [comment]
Hi, SLB does not have any control over the display of thumbnail images on the page.  It only controls what happens when image links are clicked (e.g. displays images in a lightbox).

Also, SLB only supports the version of jQuery officially included and supported by WordPress itself.  See here for [more information on jQuery support](https://github.com/archetyped/simple-lightbox/wiki/jQuery-Support).
