### ISSUE TITLE
Issue: simple lightbox not working since latest wordpress update

### ISSUE THREAD

**Issue by baconjam** [archetyped/simple-lightbox#452]
## Description of Problem
We love lightbox, however since we applied the Wordpress 4.4 update and updated the 2014 theme any new uploaded images are not recognised by lightbox.
All previous images continue to display fine.
## Details
http://rosemaryandporkbelly.co.uk/ready-steady-cook/
Browser: Firefox
Version of SLB Installed: Version 2.5.2

**Comment by n01d3a** [comment]
I am also not able to get simple lightbox to work. I have setup a new test site, using Wordpress 4.4, default 2016 theme, and no other plugins. When I click on an image it opens a new page with only the image on it.

**Comment by archetyped** [comment]
Hi @baconjam, there do not appear to be any image links at the link you provided, but rather just plain images.  Without links, there is nothing for visitors to click on for to launch the lightbox.  See [WordPress' official documentation on specifying links when inserting images from the media library](http://codex.wordpress.org/Inserting_Images_into_Posts_and_Pages#Image_Link).

Once the links are added, the linked image should be displayed in the lightbox.

@n01d3a similar issues may be caused by completely different reasons.  Please [create a new ticket](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support) specifically for your issue and I would be glad to take a closer look.

**Comment by baconjam** [comment]
Hi

Thanks for the quick response. Of course when I updated wordpress it 
defaulted to base settings which I had not noticed.

I now feel very silly!

Cheers,
baconjam


On 19/12/2015 00:10, Archetyped wrote:
>
> Hi @baconjam <https://github.com/baconjam>, there do not appear to be 
> any image links at the link you provided, but rather just plain 
> images. Without links, there is nothing for visitors to click on for 
> to launch the lightbox. See WordPress' official documentation on 
> specifying links when inserting images from the media library 
> <http://codex.wordpress.org/Inserting_Images_into_Posts_and_Pages#Image_Link>.
>
> Once the links are added, the linked image should be displayed in the 
> lightbox.
>
> @n01d3a <https://github.com/n01d3a> similar issues may be caused by 
> completely different reasons. Please create a new ticket 
> <https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support> specifically 
> for your issue and I would be glad to take a closer look.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/archetyped/simple-lightbox/issues/452#issuecomment-165924843>.
>
> No virus found in this message.
> Checked by AVG - www.avg.com <http://www.avg.com>
> Version: 2016.0.7294 / Virus Database: 4489/11213 - Release Date: 12/19/15
>




-----
No virus found in this message.
Checked by AVG - www.avg.com
Version: 2016.0.7294 / Virus Database: 4489/11213 - Release Date: 12/19/15
