### ISSUE TITLE
Issue: Plugin stopped working

### ISSUE THREAD

**Issue by tycooko** [archetyped/simple-lightbox#461]
## Description of Problem

The plugin worked great for like months and today it just stopped working, as you can see from this gallery page: http://www.psmtickling.com/models/leon/ .
It doesn't enlarge the images in the same page as it's supposed to do. The links to the original pic get opened in a new page as if there wasn't any plugin uploaded.

## Details

* URL of Page exhibiting problem: http://www.psmtickling.com/models/leon/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all of them (I tried on Chrome, Firefox and Safari on a Mac and Chrome, Firefox and Internet Explorer on a Windows)
* Version of SLB Installed: 2.5.2
* Other plugins installed: Akismet, BackWPup, Calendar Category, Contact Form 7, Count Per Day, Custom Category Post Order, Disqus Recent Comments Widget, Easy Instagram, Events Manager, Feed Template Customize, Fetch Tweets, FitVids for WordPress, Fix Rss Feeds, Foo Gallery, FV Top Level Categories, Global Meta Keyword & Description, Google Analytics by Yoast, jQuery Updater, JW Player 6 Plugin for Wordpress, MailPoet Newsletters, Page Excerpt, Payhip - Sell Digital Downloads, Q2W3 Fixed Widget, Recent Facebook Posts, Regenerate Thumbnails, Shareaholic, Simple Ads Manager, Simple Links, Ultmate Tag Cloud Widget, Wordfence Security, WordPress Category Archive, WordPress Importer, WP TinyMCE Excerpt, WP-Polls, WPML Multilingual CMS, WPML Sticky Links, WTI Like Post PRO

**Comment by archetyped** [comment]
Hi, SLB does not appear to be activated at the link you provided.  Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a look.

**Comment by tycooko** [comment]
Hello. Sorry, but, naturally, replying days later could result in losing a client, which is what happened. We have dozens of thousands of visitors coming to the site every month and can't allow ourselves to have a non-functional plugin set, so we had to put another one. Thank you anyway. 


Matteo P.,PSM network Admin-------- Messaggio originale --------Da: Archetyped <notifications@github.com> Data: 04/02/2016  01:13  (GMT+01:00) A: archetyped/simple-lightbox <simple-lightbox@noreply.github.com> Cc: tycooko <admin@psmtickling.com> Oggetto: Re: [simple-lightbox] Issue: Plugin stopped working (#461) 
Hi, SLB does not appear to be activated at the link you provided.  Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a look.

**Comment by gsallman** [comment]
Me too! Since the update to WP 4.4.2 The plugin has just stopped working. It seems to work the first time you visit the site and then stops and the linked image is displayed instead.

Example page: http://www.paisleylizard.com/2016/01/buried-treasure-aje-jewelry-challenge/

To reproduce the fault you may have to click around a bit.

I tried turning off all the plugins except Simple Lightbox and it still wouldn't work. All plugins are at their latest releases.

SLB 2.5.2

Other plugins:

Bad Behavior 2.2.18
jetpack 3.9.1
VaultPress 1.7.8
Yoast SEO 3.0.7

and my own shortcodes plugin (which just creates css text wrappers and has been working for several years, no changes have been made)

**Comment by soccersnyderi** [comment]
Same is happening with my site, since updating to WP 4.4.2 Occasionally, Lightbox goes back to working fine, but not for long, and then it's back to sending you to a separate page to see the original image size. 

Example page: http://www.brickbuilt.org/?p=3213

The problem exists in all browsers I've tested, Mozilla Firefox, Chrome, Internet Explorer.

I too tried turning off all other plug ins, and still had the same issue.
Plug ins:
Akismet
Cryout Serious Theme Settings
Enhanced Media Library
MOJO Marketplace
Official Statcounter 
Wordpress Importer
WP Rollback

Theme is Tempera

**Comment by archetyped** [comment]
Hi @gsallman, I tested all of the images on the page you provided and SLB worked properly for all of them.  If you are still experiencing an issue, please create a new ticket for your specific issue (that may not be related to the OP's issue) so that it can be evaluated further.

Thanks.
