### ISSUE TITLE
Issue: Simple Lightbox not working when site content is over https

### ISSUE THREAD

**Issue by bpazbc** [archetyped/simple-lightbox#506]
## Description of Problem
I have recently installed the simple lightbox plugin and testing over http works without issue, however our production site is over https and this seems to break the functionality of the plugin. 

## Details

* URL of Page exhibiting problem: internal (private/not publicly accessible)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): IE, Firefox, Chrome
* Version of SLB Installed: 2.5.3
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB has been tested extensively for functionality over HTTPS.  In fact, [SLB's own home page is served over HTTPS](https://archetyped.com/tools/simple-lightbox/).

Your issue may be due to a different reason such as a conflict with another plugin or server configuration.  I would be glad to take a look if you can provide a link to a page that exhibits the issue you are experiencing (a temporary/staging site is fine if you are unable to share a link to your production site).

**Comment by bpazbc** [comment]
Hi, thank you for your response. Unfortunately I have no way of providing an external link as this site is only accessible over our private network. The plugin functions perfectly on my site when I access the page over http, but not over https. I was suspecting that this may be a browser security issue if the plugin was in any way trying to access external resources over http causing mixed content within the page. I will try to look further into this when time allows. I appreciate your help.

**Comment by archetyped** [comment]
No problem.  Here are [some things you can look into to help track down the cause of the issue](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support#self-serve-support).

I am closing this ticket, but I would be glad to reopen it if/when you are able to reproduce your issue on a public-facing site (even a temporary dev server) that I can take a closer look at.
