### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by maryvoss** [archetyped/simple-lightbox#508]
## Description of Problem
Problem with the lightbox add on to word press, it seems to open a double version of an image when I click on a linked photo.  

## Details

* URL of Page exhibiting problem: http://www.foodphreaque.com/index.php/2016/08/22/making-pasta-easier-than-you-think/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: Simple Lightbox 2.5.3
* Other plugins installed: There are other plug ins but nothing that effects anhything with images.

**Comment by archetyped** [comment]
Hi, you may be surprised that plugins that don't seem to have anything to do with images can impact other plugins that do, which is why this information is requested to fully evaluate your issue.

In this case, it appears that your theme is also loading a lightbox, which is opening when links are clicked.  I would recommend checking your theme's options for a setting to disable this lightbox.  If you cannot find a setting, I would recommend contacting the theme's developers for instructions on disabling it.
