### ISSUE TITLE
How to speed up lightbox

### ISSUE THREAD

**Issue by georgemind** [archetyped/simple-lightbox#515]
Hi there,

I am finding that each image in lightbox is very slow to load. Is there anything I can do to speed this up?

**Comment by archetyped** [comment]
Hi, image loading speed is largely dependent on the size of the image files and your internet connection speed.

There are several things you can do to optimize an image's file size so that it downloads faster.  For example:

* Change the file format (e.g. use JPEG instead of uncompressed PNG)
* Increase compression
* Resize images to fit most users' screens
