### ISSUE TITLE
Issue: Captions do not display when using slb_activate()

### ISSUE THREAD

**Issue by etellewyn** [archetyped/simple-lightbox#530]
## Description of Problem
When a page is controlled by a custom theme template file, and the content is run through slb_activate() to generate lightbox, image captions do not display. These only display when using the normal content editor. 

When inspecting the output, I just see an empty div where the caption should be... <div class="slb_data_desc"><span class="slb_template_tag slb_template_tag_item slb_template_tag_item_description"></span></div>

## Details

* URL of Page exhibiting problem: 
[this is a temporary staging site during development] http://bluestem.wizzywigwebdesign.com/project/test-premier-project-with-slider/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Tested in Chrome, Firefox, Safari on mac

* Version of SLB Installed: 2.5.3

* Other plugins installed: Conflict tested against all but custom theme, CPTUI and ACF Pro (which are required for functionality). For list of installed plugins, see https://nimbus.everhelper.me/client/notes/share/592383/bno80xz06d3gkhca0zll

**Comment by archetyped** [comment]
Hi, are all image links on that page activated by `slb_activate()` or only certain ones?  All image links I tested appear to be displaying a caption in the lightbox, so please let me know if there is a specific image that is not displaying a caption.

Thanks.

**Comment by etellewyn** [comment]
Thanks for your response. It is all of them (since all images are ACF gallery or repeater fields). For example, scroll to the Before & Afters section, and click on the first image (upper left on medium and large screens). You will see the caption shown there in transparent black before you click -- it should read "Test caption inventore sequi, alias voluptatem". Instead just the title of the image appears. Another example is found down further in the "Project Gallery" section. Again you can see the images which have captions, in the transparent black overlay. But when you click on the image, only the image title appears in the SLB modal.

**Comment by archetyped** [comment]
Hi, SLB displays a link's `title` attribute when one is set.  Otherwise, the caption is displayed as a fallback.  The links on your page have `title` attributes, which may be set by the theme/plugin used to output the image links, so this is what is being displayed in the lightbox.

See SLB's documentation for [full details on how the lightbox's title's value is determined](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence).

Note that you can also display additional data _below_ the title in the lightbox by adding content to the image's **Description** field in the media library.

**Comment by etellewyn** [comment]
Interesting! Yep I have removed the title attribute from the anchor and this has allowed the caption to display as expected. Glad to know it was an easy fix. Thank you very much for your prompt help!
