### ISSUE TITLE
Slideshow won't restart

### ISSUE THREAD

**Issue by CastonWebDesigns** [archetyped/simple-lightbox#552]
## Description of Problem
Slideshow starts automatically but if slideshow closed down then clicking the gallery image again or clicking another image, the slideshow will not restart.  The only way to restart is to refresh the page.  Pity, I really liked this plug in until that problem became apparent.  I do hope you have a solution.

## Details
* URL of Page exhibiting problem:   http://428.d39.myftpupload.com/robs-water-images/ 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox automatic update to latest version
* Version of SLB Installed: SLB v2.6.0
* WP version: WP v4.7 running Divi Child Theme
* Other plugins installed: Child Theme Configurator; Official Statcounter plugin; TinyMCE Advanced

**Comment by archetyped** [comment]
Hi, it looks like you have another lightbox plugin on the page (Magnific Popup).  Multiple lightbox plugins can cause conflicts because they're all designed to react to a link being clicked.

Disabling the other lightbox plugin should allow SLB to function normally.  If you are still experiencing issues after disabling the other lightbox, please update this ticket with additional details and I would be glad to take another look.

**Note:** If the lightbox is installed as a separate plugin, then it may be included as part of your theme.  If there are no options to disable the lightbox via theme's settings, I would recommend contacting the theme's developers for instructions on disabling the lightbox.

**Comment by CastonWebDesigns** [comment]
Thank you for this really quick reply.  Magnific Popup is built in to the Divi theme and I now see a number of users have had the same problem and disabled it which I’ve now done and it is working well with one very small issue which if you can solve or help me with I’ll be grateful.  Click on an image and the lightbox opens and is on play.  Once you close the lightbox when it reopens it is on pause.  Can it re-open on play or is that not possible?

 

Again thank you for your interest.

 

Kind regards

 

Brian 
Caston Web Designs

www.castonwebdesigns.co.uk   Skype: brian-brooker

01953 488 477                                               07899 652 262

E-Mail Signature

This email and any files transmitted with it are confidential and intended solely for the use of the intended recipient. If you have received this email in error please notify the sender. If you are not the intended recipient you must not disseminate, distribute or copy this e-mail. Please be good enough to notify the sender immediately by e-mail if you have received this e-mail by mistake and delete it from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the content of this information is strictly prohibited.
