### ISSUE TITLE
Issue: Conflict with other lightbox

### ISSUE THREAD

**Issue by corendesign** [archetyped/simple-lightbox#566]
**Problem**: using your lightbox produces 2 lightbox slideshows on top of each other with my Divi slider. Any suggestions how to limit Simple Lightbox to work only with Meta Slider and Carousel only?

Using Meta Slider and Carousel with Lightbox, example: http://5e0.bd5.myftpupload.com/edwin/ (**Works great**.) 

Using Divi (theme) slider: http://5e0.bd5.myftpupload.com/esmeraldas-ecuador/ (**Problematic**.) 

* URL of Page exhibiting problem: http://5e0.bd5.myftpupload.com/esmeraldas-ecuador/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all
* Version of SLB Installed: 2.6.0
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, you can exclude parts of a post using SLB's `[slb_exclude]` shortcode.  See [SLB's shortcode documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes) for more details.

Alternatively, you may also look into whether your theme's lightbox can be disabled, so that only SLB is displayed when a link in the Divi slider is clicked.
