### ISSUE TITLE
Issue: Lightbox loading at bottom of page

### ISSUE THREAD

**Issue by konsu7** [archetyped/simple-lightbox#572]
## Description of Problem

The lightbox is loading at the bottom of the page.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, this is usually caused by invalid HTML being rendered on the page.  The invalid HTML stops the web browser from properly rendering the page's elements, such as the position of the lightbox.

Please fill in the details of your request above (including a link to a page exhibiting the issue), and I would be glad to take a closer look.

**Comment by marthaSplatterHead** [comment]
Same issue when I click next photos it moves further down the page all tags accounted for

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.

@marthaSplatterHead please [create a separate ticket](https://github.com/archetyped/simple-lightbox/wiki/Reporting-Issues) for your specific issue so that it can be attended to individually.

Thanks.
