### ISSUE TITLE
Miscount on single image

### ISSUE THREAD

**Issue by manesal** [archetyped/simple-lightbox#592]
When applied to a single image, the lighbox shows "Item 1 of 2" and shows the same image twice .

I saw antoher thread about miscount, but my situation is a little bit different...

Details

URL of Page exhibiting problem: http://www.eisenia.com.br/
Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome / Versão 58.0.3029.96 (64-bit)
Version of SLB Installed: Versão 2.6.0

**Comment by archetyped** [comment]
Hi, the page you provided has two links that point to the same image.  As many users may include multiple links to the same image for different reasons, SLB does not make any assumptions about whether each instance should be displayed in the lightbox.

You can use the `[slb_exclude]` shortcode ([documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes)) to exclude a link if you do not want it to be displayed in the lightbox.  Alternatively, you can turn off grouping via SLB's settings so that each image is displayed independently (i.e. no "Item x of y" text).
