### ISSUE TITLE
Light box not working in Post pages in wordpress

### ISSUE THREAD

**Issue by soumodev07** [archetyped/simple-lightbox#612]
Hello there. I have an issue with the simple lightbox plugin. It worked fine in local host server but when I transferred my site to a new domain it stopped working. Now when I click on an image it opens the actual image URL and not a lightbox. I tried uninstalling the plugin and reinstalling it but in vain. Here is the link to my blog page. Please help me in solving this issue
http://knowyourgadget.host22.com/asus-zenfone-2-laser/

**Comment by RelicUK** [comment]
Hi Soumodev07, I've got the some issue on the site I'm working on. How did you fix this?

**Comment by archetyped** [comment]
Hi, SLB appears to be working properly at the link you provided.  If you are still experiencing this issue, please provide additional details and I would be glad to reopen this ticket.

@RelicUK please [create a separate ticket for your issue](https://github.com/archetyped/simple-lightbox/wiki/Reporting-Issues) so that it can be fully evaluated.

Thanks.

**Comment by soumodev07** [comment]
@RelicUK I just deactivated all the plugins and I simply activated the Simple Light Box(SLB) Plugin first to check if it was working properly or It really had an issue. I found it was working properly and then i started re-activating all the plugins one by one to find the culprit. In my case it was the Buddy Press plugin which stopped the SLB to function properly. I uninstalled it and the Light Box was back....
