### ISSUE TITLE
Issue: Not working anymore on https protocol

### ISSUE THREAD

**Issue by robertomarassi** [archetyped/simple-lightbox#624]
## Description of Problem
After activating the https (ssl) protocol the plugin seems not working anymore; on my local version (on localhost) or on http protocol is working fine, as usual. Any idea? Thanks

## Details
Same issue on all my sites with https protocol; if on http works fine (i.e: http://www.kellerimmobiliare.it/immobile/appartamento-2-locali-a-milano-zona-duomo-san-sepolcro/)
* URL of Page exhibiting problem: https://erik.marassiweb.com/prime-uscite-sul-420/
https://bibliotecalongone.marassiweb.com/budget/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): firefox, chrome, chrome on tablet
* Version of SLB Installed: 2.6.0
* Other plugins installed: all disactivated

**Comment by portablestaging** [comment]
My lightbox no longer functions. Not sure whats happened I guess an update. Worked fine. Now visitors are leaving to watch on YouTube - Video image is link here in text - https://www.portablestage.co.uk/listing/nexgen-hardboard-fascia-skirt/ 
Click to see.
Any advice would be helpful

**Comment by Lhaz** [comment]
Same here : http://www.hokutolegacy.com/2017/10/24/un-premier-apercu-de-regenesis/

**Comment by archetyped** [comment]
@robertomarassi: Please provide details on how you switched to https (via plugin, server configuration, etc.).  If you are using a plugin, please provide a link.

@portablestaging: Please [create a separate support ticket](../wiki/Reporting-Issues) so that your specific issue can be evaluated directly.

@Lhaz: SLB appears to be functioning at the link you provided.  If you are still experiencing an issue, please [create a separate support ticket](../wiki/Reporting-Issues) so that your specific issue can be evaluated directly.

Thanks

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. @robertomarassi, if you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
