### ISSUE TITLE
Doesn't work.  SSL bug?

### ISSUE THREAD

**Issue by xanderak** [archetyped/simple-lightbox#645]
## Description of Problem

When clicked, the image opens on a new page, as if SLB plugin did not exist.

Here are what the media thumbnail links look like in view source. 

`<a href="https://example.com/wp-content/uploads/2018/02/logo6icon.png" data-slb-active="1" data-slb-asset="953101106" data-slb-internal="0" data-slb-group="145"><img class="alignnone wp-image-135 size-medium" src="https://example.com/wp-content/uploads/2018/02/logo6icon-300x300.png" alt="" width="300" height="300" data-headline="logo6icon" srcset="https://example.com/wp-content/uploads/2018/02/logo6icon-300x300.png 300w, https://example.com/wp-content/uploads/2018/02/logo6icon-150x150.png 150w, https://example.com/wp-content/uploads/2018/02/logo6icon.png 512w" sizes="(max-width: 300px) 100vw, 300px"></a>`

Doesn't matter if I use my custom theme or the default TwentySeventeen theme.

More details:
If I disable the SSL certificate on Bluehost it works.
Other lightbox plugins seem to have the same issue, not working if I turn on SSL.
If I hard-code the lightbox to individual thumbnails it works.
ACF plugin works fine whether SSL or not.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by joshfttb** [comment]
I'm experiencing this same problem, I'm on WPEngine.

**Comment by Beee4life** [comment]
I run this plugin on an SSL [website](https://internationaldownhillfederation.org/2017/kozakov-challenge-shows-a-high-skill-level/) without any issues.

**Comment by DN-FS** [comment]
Same here. It worked fine on a non SSL testsite (different domain) and stopped working on the final SSL domain. Any news regarding this issue?

**Comment by archetyped** [comment]
Hi @xanderak Simple Lightbox is fully compatible with sites that use SSL.  However, it sounds like your site may not be properly configured for SSL since other plugins are not working properly either.

This can occur when using a plugin to "enable" SSL for a site that was not originally set up with SSL from the start.  In many cases, URLs need to be updated at the database level to work properly.

Post a link to a page if you are still experiencing an issue with SLB once you get the general SSL issues resolved and I would be glad to reopen this ticket and take a closer look.

**Others posters:** Please [create a separate ticket](https://github.com/archetyped/simple-lightbox/wiki/Reporting-Issues) so that your specific issue can be evaluated properly.

Thank you.
