### ISSUE TITLE
Issue: Popups appear below visible area of window in "Editorial" theme

### ISSUE THREAD

**Issue by tommcgee57** [archetyped/simple-lightbox#667]
Popups appear below visible area of window

## Details
Theme is "Editorial." The problem doesn't show up in Twenty Fifteen.

* URL of Page exhibiting problem:  http://tom-mcgee.com/archives/6670 (I've added some CSS rules to ameliorate the problem, but you can disable them to see what happens)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  Chrome and Firefox
* Version of SLB Installed: 2.7.0
* Other plugins installed: Lots, but changing to a default theme made the problem go away.

**Comment by archetyped** [comment]
Hi, display issues like you describe are most commonly caused by invalid HTML used by the theme.  As the issue is resolved when switching to a theme with valid HTML (such as Twenty Fifteen), this is most likely the cause in your case as well.

You can see what is causing the invalid HTML using this tool: [W3C's HTML Validator](https://validator.w3.org/).  Once identified, I would recommend contacting the theme's developer to have the issue resolved.
