### ISSUE TITLE
Issue: Lightbox not showing all metadata/custom meta

### ISSUE THREAD

**Issue by kvalinote** [archetyped/simple-lightbox#714]
## Description of Problem

Lightbox is only showing image caption.

![e627a9b921d131459058c7e4e12637e4](https://user-images.githubusercontent.com/20914492/53256086-1319dd80-3695-11e9-9964-550f9a3bba92.png)

I need to be able to show image title, caption, description, category, and photo credit metadata in the lightbox view.

![036b410db64573d3c251ee3a107d1511](https://user-images.githubusercontent.com/20914492/53256398-c551a500-3695-11e9-8d29-39b82cd1bdcb.jpg)

![226e50becf6e99c043f865fc198303bd](https://user-images.githubusercontent.com/20914492/53256108-1f059f80-3695-11e9-87ce-96ba24193709.png)

## Details

* URL of Page exhibiting problem: https://htbeta.com/vf/photo-search/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Firefox
* Version of SLB Installed: 2.7.1
* Other plugins installed: 
![e4e19dbf7f22d063497ef6728ff59b07](https://user-images.githubusercontent.com/20914492/53256299-84f22700-3695-11e9-9827-22cec17ee0b1.png)

**Comment by archetyped** [comment]
Hi, based on the screenshot you provided, the attachment does not have a description.  If you add a description for the attachment, then it should be displayed in the lightbox. 

If you are still not seeing a description in the lightbox after adding a description to your attachment(s), then please provide an updated link to a page that exhibits the issue and I would be glad to take a closer look.

Non-standard (i.e. custom) attachment metadata fields would need to be supported via an add-on to provide SLB with details on how the fields' values should be retrieved, formatted, etc.  Are you using a particular plugin to add the custom metadata fields?  If so, please provide a link to the plugin so I can take a closer look.

Thanks.

**Comment by kvalinote** [comment]
Hi, thank you for the response.

We have a custom attachment meta field for "photo credit" which is using the Advanced Custom Fields PRO plugin: https://www.advancedcustomfields.com/

We also have another custom meta for attachments, which are category boxes. The desired effect would be to show the selected categories in the lightbox view. The plugin we use for this is Media Library Categories Premium: https://wordpress.org/plugins/wp-media-library-categories/

![216f61cc620133f2209c981852a28687](https://user-images.githubusercontent.com/20914492/53664353-47ae0c00-3c36-11e9-8ea4-969e3e6bfc9d.jpg)


Please let me know if this is possible to implement, and how to please.

Also, I noticed that the lightbox doesn't generate sometimes, and clicking on an image will load the image URL instead of the lightbox view. It seems this happens every other image click.

Thanks!

**Comment by archetyped** [comment]
Hi, as different plugins may store additional metadata differently, a custom add-on is generally required to support extra metadata added by a specific plugin. 

You can add your comments and requests to [the existing ticket for an ACF add-on](https://github.com/archetyped/simple-lightbox/issues/527), and if desired, you can [create a new feature request](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support#feature-requests) for a Media Library Categories add-on.

As for the lightbox sometimes not loading, it appears that the theme or another plugin is resetting the gallery content after a couple clicks.  This severs the connection between the image links and SLB, which is why images are loaded directly in the browser, rather than being displayed in a lightbox.

It appears that this may be due to the **FacetWP** plugin, but you can [confirm the conflicting theme or plugin using the following instructions](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).  Once the conflicting theme or plugin has been identified, please provide the name and link to the theme/plugin and I would be glad to take a closer look.

Thanks.
