### ISSUE TITLE
Support for the <picture> element and srcset="" attibute ?

### ISSUE THREAD

**Issue by nylnook** [archetyped/simple-lightbox#719]
Hi, and thanks for your plugin !

It's perfectly what I need, but my customized theme is using the HTML5 _picture_ element instead of _img_ to have really responsive pictures : I tried to add your lightbox to these picture elements with `slb_activate($content)` but it's doesn't activate the link and lightbox. 

Do you think it's possible for your plugin to be activated not only on 
 `<a href=""><img src=""></a>` HTML markup structure, 
but also on
```
<a href="">
  <picture> 
      <source="">
      <source="">
      <img src="">
  </picture> 
</a>
```
structure ?

I also tried with the _srcset_ attribute inside _img_, the plugin work but the browser (Firefox or Chrome) seem to load only the _src_ element anyway.

I can modify my theme code to make it work with simple _img_ elements, but that's an optimization I'd like to keep as far as possible.

Thanks a lot for your answer ;)

**Comment by archetyped** [comment]
Hi, SLB is agnostic about the markup that is wrapped by a link, so `<picture>` elements within the link should not prevent SLB from displaying the linked content at all.

Keep in mind that SLB displays the content from the **link** (i.e. the value of the link's `href` attribute).  If you are seeing the lightbox display the same content as an enclosed image's `src` attribute, then that is most likely because it is the same content set as the link's `href` attribute.

If you are experiencing different behavior than described above, please provide an example of how you are activating the links (e.g. using `slb_activate()`) in your theme's markup as well as a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by nylnook** [comment]
Ok, my fault, I don't know what I did wrong previously, but checking again it do work with 
```
	$lightbox = '<a href="' . get_the_post_thumbnail_url($thumbID, 'full') . '"><img src="' . get_the_post_thumbnail_url($thumbID, 'huge') . '" alt="' . get_the_title($thumbID) . '" /></a>';
	if ( function_exists('slb_activate') ) {
		$lightbox = slb_activate($lightbox);
	}
	echo $lightbox;
```

but also with 
```
	$lightbox = '<a href="' . get_the_post_thumbnail_url($thumbID, 'full') . '">
						<picture>
							<source srcset="'. get_the_post_thumbnail_url($thumbID, 'huge') . '" media="(min-width: 1901px)"></source>
							<source srcset="' . get_the_post_thumbnail_url($thumbID, 'large') . ' 1x, ' . get_the_post_thumbnail_url($thumbID, 'huge') . ' 2x" media="(min-width: 1581px)"></source>
							<source srcset="' . get_the_post_thumbnail_url($thumbID, 'medium_large') . ' 1x, ' . get_the_post_thumbnail_url($thumbID, 'extra_large') . ' 2x" media="(min-width: 981px)"></source>
							<source srcset="' . get_the_post_thumbnail_url($thumbID, 'medium') . ' 1x, ' . get_the_post_thumbnail_url($thumbID, 'large') . ' 2x" media="(min-width: 481px)"></source>
							<source srcset="' . get_the_post_thumbnail_url($thumbID, 'thumbnail') . ' 1x, ' . get_the_post_thumbnail_url($thumbID, 'medium_large') . ' 2x"></source>
							<img srcset="' . get_the_post_thumbnail_url($thumbID, 'medium_large') . '" alt="' . get_the_title() . '" />
						</picture>
						</a>';
	if ( function_exists('slb_activate') ) {
		$lightbox = slb_activate($lightbox);
	}
	echo $lightbox;
```

maybe you should give theses examples in your documentation for stupid folk like me doing syntax errors ;)

If you want to see it running : [https://nylnook.art/en/](https://nylnook.art/en/) (on single post pages)

Thanks for you time and for your great plugin !
