### ISSUE TITLE
Issue: Grouping of Elementor Galleries

### ISSUE THREAD

**Issue by mr-imaginativ3** [archetyped/simple-lightbox#724]
Sorry about the issue title.. really not sure how to describe in few words.

## Description of Problem
Why does the SLB not distinguish between galleries sets in the lightbox slideshow? I have several Elementor carousel galleries on one page with different sets of images.  http://janneteau.org  Why does the slide show not exclusively show the images from the one carousel gallery I just clicked on?  It currently goes from the last image of the gallery I just clicked on to the first image of the next carousel gallery.

Also I find your grouping settings language to be quit difficult to understand. I think you need to rework the language using a newbie as a writer. I am available ;-)

## Details

* URL of Page exhibiting problem: http://janneteau.org
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Edge, Chrome, Firefox
* Version of SLB Installed: Installed today so latest
* Other plugins installed: They are all up to date as of sending this message
Customizer Export/Import NOT ACTIVE
Elementor
Select Essential Addons for Elementor	
EWWW Image Optimizer
Mobile Menu	
NavMenu Addon For Elementor	
Simple Lightbox	
Swift Performance Lite	NOT ACTIVE
WP Rollback
WP User Avatar

**Comment by mr-imaginativ3** [comment]
Because you didn`t answer I removed the pluggin from my site.

**Comment by archetyped** [comment]
Hi, please note that SLB's built-in grouping functionality is primarily designed to work with WordPress' own built-in gallery functionality.

Since various plugins (such as Elementor) implement their own gallery functionality differently than WordPress itself, plugin-specific functionality generally will need to be supported via an add-on.  You can [create a request for a new add-on](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support#feature-requests), which are developed based on user feedback and demand.

Also, I am open to any specific feedback on SLB's settings language that you may have.  Please let me know how "Group items (for displaying as a slideshow)" is confusing and your suggestions for what changes would be made, and I would be glad to take a look.

Thanks.
