### ISSUE TITLE
Request: 

### ISSUE THREAD

**Issue by TrevisNL** [archetyped/simple-lightbox#726]
## Description of feature/request

Hi there, maybe it is already available but can't really find it.. I would love a function where you can make a grouped Lightbox (so you click on an image, and you have a video Lightbox) but you can go to the left and right. 

## This feature would be used to

Make an portfolio with categories, if you click on the image (category) you will see all video's within that category

## If you added this feature, I would:
D, and finally finish my project, SO THAT WOULD BE GREAT <3

**Comment by archetyped** [comment]
Hi, images can be grouped to be displayed as a slideshow in the lightbox by enabling the "Group items (for displaying as a slideshow)" option in the **Grouping** section of SLB's admin settings.

If you are still experiencing an issue after enabling grouping, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to reopen this ticket and take a closer look.

Thanks.

**Comment by TrevisNL** [comment]
Hi there, I just bought your video add-on.

http://test.treviant.nl/woutersessink/blog-dark-landing-v3/

I would like to have a grouped video viewer when I click on for instance 'trailers' or 'leaders' or whatever. so the trailers section should lead to a couple of video's. the leaders section should lead to a couple of different video's..

How can I do this?
Thank you so very much :)

**Comment by archetyped** [comment]
Hi, you can use [this tutorial on how to launch a slideshow from a single link](https://archetyped.com/know/slb-single-link-slideshows/ "Simple Lightbox: Launching Slideshows from a Single Link - Archetyped") to display a group of videos in the lightbox by clicking a single link on the page.

In order to create separate groups in the same post, wrap each group of links in the `[slb_group]` shortcode.  See [SLB's shortcode documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes#slb_group) for more details.
