### ISSUE TITLE
Issue:  Z-axis setting for lightbox 

### ISSUE THREAD

**Issue by docakp** [archetyped/simple-lightbox#737]
## Description of Problem
When pop up, some light box pop ups are behind some pop up ( example, woo-commerce quick view ) especially when try to view the pictures from products.

There should be a place to put Z-axis value like 999999 
As I do not know code knowledge, I am making this request.

I also purchased Simple Lightbox: Video Handler as well.

Thanks.
Regards,
Aung

## Details

* URL of Page exhibiting problem: 
https://www.havenofjoy.com/shoppage
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
Safari
* Version of SLB Installed: 
2.7.1
* Other plugins installed: 
Simple Lightbox: Video Handler 0.2.0

**Comment by archetyped** [comment]
Hi, the link you provided has not been accessible whenever I've tried to check it.  Please check the link and post and update when the link is available, and I will take another look.

Thanks.

**Comment by docakp** [comment]
Hi,
Very sorry about it.
I am migrating my website to better hosting. Now finished.

I want to ask you regarding a few issues.

I purchased your plug in ( video light box as I love simple lightbox and wish to be your customer ), I know simple lightbox is free but video lightbox add on, I purchased with 50% off. 

I purchased because your lightbox could detect all the media in a page automatically and open light box clicking even on link (for the media embed).

Most of all, I remember...it can pop up over a pop up box ( Pop Up anything on click plug in ).( Double pop up )

1. Now with version 2.7.1 when I updated, that function is gone.
Only on the ordinary web-page, your light box pop up and show and 
another issue is , in the setting, I could not turn off "photo heading or link showing beneath the photo " not to show photo name or link.

 Please kindly check,

https://www.medrectaker.com <https://www.medrectaker.com/>

User name : chanmoeaung
Password: SimpleLightBox

Please click  number 1 picture icon and you will see on first top post, there are 2 links for the pictures uploaded to the media library.
Before, they pop up in light box.
Now, they open new tab. 

Please kindly test and tell me how I can get the above mention function.
Pop up light box on the pop up box. 

Hope that you can help me with this issue as I want this pop up lightbox over pop up.
Otherwise, no meaning.


2. Can simple light box create preview on the link (like uploaded link in my example home page)?


3.One last question,
For video light box beta, can I use it on multiple sites?
For the price, I purchased, how many websites am I allowed to install and use?
I have 3 websites. 

Regards,
Aung Khine

**Comment by archetyped** [comment]
Hi, posting login information in a public forum is not recommended.  I have removed it from your post, but I would recommend changing whatever login it was for to avoid anyone else from accessing your site.

Regarding your questions:

* Pop up over a pop up box: Please provide the version of SLB where this functioned as you describe and a link that demonstrates the functionality so that I can evaluate it.
* Could not turn off "photo heading or link showing beneath the photo" setting: SLB does not have such a setting.  Please provide screenshot and more details of the setting you are referring to.
* Create preview on the link: Please provide more details on what you mean by "create a preview on the link" and which link on the example home page you're referring to.
* Video add-on: the add-on is licensed for a single site.  Once the beta period is completed, there will be additional licensing options, including for multiple sites.

**Comment by docakp** [comment]
Hi,

Sorry about including log in credentials.

How can I send you the information in case necessary?

1. I dont remember the exact version but I can tell just before 1 or 2 updates. I tried to go back to 1.6 and not okay.

2. I mean the title of the photo. I will attach screen shot here.

3. For example, https://www.dropbox.com/s/di5uj6qy2pmgfx6/Screenshot%202019-08-17%2019.01.50.png?dl=0 <https://www.dropbox.com/s/di5uj6qy2pmgfx6/Screenshot%202019-08-17%2019.01.50.png?dl=0>

That is the link. I want simple light box plug in to read the media link and create small or medium or large preview thumbnail photo or media to display instead of that plain link.


4. Thank you. I would like to purchase video add on for multiple sites.



Thank you.

Regards,
Aung Khine




There is a sentence below the picture. Is not it a title/heading of the photo?


Thanks.

Regards,
Aung Khine

**Comment by archetyped** [comment]
Thank you for the additional information.

1. Pop up over a pop up box: Generally speaking, using multiple lightbox popup/lightbox plugins at the same time is not recommended as they are all designed to display over other content, which can lead to issues like you describe.  If it worked before, it was not by design, and it's possible that the other plugin may have changed something in an update that affected the unexpected compatibility.
2. Photo title: I don't think email attachments work for GitHub's forum.  You need to post directly in the forum thread (i.e. not via email) to upload an image.  Alternatively, please provide a link to a page that exhibits the title you do not want to display and I would be glad to take a look.
3. WordPress automatically creates smaller versions of uploaded images.  See [WordPress' documentation on inserting images into posts](https://wordpress.org/support/article/inserting-images-into-posts-and-pages/) for full instructions on inserting smaller versions of an image into a post.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
