### ISSUE TITLE
Not working on CPT on Wordpress

### ISSUE THREAD

**Issue by imboldlygoing** [archetyped/simple-lightbox#759]
## Description of Problem

Hello,
I have been able to use simple lightbox on posts and pages, but just **can't seem to enable them on  a CPT single**. 
I'm using elementor, so all my CPT theme files have the_header, the_footer and the_content. 
Also, I am not declaring my CPT on funcions, rather using a CPT UI Plugin. I'm not sure if that is the problem...

I've already tried troubleshooting with a default theme and deactivating all other plugins except for ACF PRO (which I use to populate this CPT), Elementor, Elementor Pro and Simple Lightbox.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please update your original post with the necessary details to evaluate your issue and I would be glad to take a look.

**Comment by imboldlygoing** [comment]
**URL:** https://7lm.com.br/?imovel=park-prime-sul
**Browser:** Chrome and Firefox
**Version:** 2.7.1
**Other plugins installed:** 
Advanced Custom Fields PRO
Autoptimize
Contact Form 7
Custom Post Type UI
Elementor
Elementor Pro
Flamingo
Imagify
Insert Pages
Insert PHP Code Snippet
Integração RD Station
Masks Form Fields
Safe SVG
Search & Filter
Simple Lightbox
WhatsApp Chat
WhatsApp Chat PRO
WP Mail SMTP
Yoast SEO

**Comment by archetyped** [comment]
Hi, I've tested Elementor's carousel widget in a CPT built with Custom Post Type UI and SLB functioned normally when clicking on those images.

Here are the only widget settings that are changed from their defaults:

* Link: Media file - so that there is something for visitors to click on.
* Lightbox: No - disables Elementors built-in lightbox.

If you are still experiencing an issue after confirming that you are using the above settings, please provide additional details, such as:

* Specific Elementor widget you are using to add the images to the CPT.
* Template code used for the CPT you are experiencing an issue with.
* A link to a CPT post exhibiting the issue - the previously-provided link does not appear to have SLB activated on it.

Thank you.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
