### ISSUE TITLE
Feedback: PHP 7.2 minimum = #fail

### ISSUE THREAD

**Issue by PattayaWeb** [archetyped/simple-lightbox#760]
I don't know why you would set a PHP 7.2 minimum when no one else is currently doing that. We'll now toss your product off our site and use one from a more sensible developer so we don't have to look an a warning in our  backend dashboard every day, all day. Really phucking stupid IMO, and my opinion is all that matters when it comes to our news site. Out of 52 plugins we currently use YOU are the only developer to insist on a PHP 7.2 minimum.

**Comment by archetyped** [comment]
Hi, the code used in SLB 2.8.0+ requires PHP 7.2 to function properly, it is not an arbitrary setting.

Nearly 30% of all plugins that specify a supported PHP version in the WordPress Plugin Directory currently require PHP 7+.  This will only increase especially since WordPress' own PHP version requirement is planned to be increased for the performance and security benefits of PHP 7+.
