### ISSUE TITLE
Issue: Upgrade impossible  - no check box

### ISSUE THREAD

**Issue by Pitpitt** [archetyped/simple-lightbox#763]
## Description of Problem

Simple Lightbox will not upgrade  because the checkbox does not appear  on update page  
and we cannot upgrade from extension page

see image capture  here :   http://ssjb.com/files/simple-lightbox.jpg

## Details

* URL of Page exhibiting problem: 
https://ssjb.com/wp-admin/update-core.php
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
Chrome AND Firefox
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, WordPress has built-in controls to prevent installing plugins/themes that your site does not support.  This is generally due to outdated software on your server.

It is cut off in the screenshot you provided, but there should be more details on why SLB's update is being blocked on your site on the line that starts with «Cette mise à jour ne fonctionne...».

SLB's documentation also has [more information on SLB's minimum requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements).

Once you've updated the necessary software, WordPress should allow SLB to be updated.  Please let me know if you're still experiencing this issue after updating the server, and I would be glad to reopen this ticket and take another look.
