### ISSUE TITLE
Lightbox not working

### ISSUE THREAD

**Issue by inasher** [archetyped/simple-lightbox#765]
Hi,
I've got the latest version of WP, just installed SLB and tested by using WP's 2020 theme with all other plugins disabled. The issue still persists.

I do have Jetpack installed with the carousel images enabled, however SLB was tested with this plugin disabled.

The issue is that SLB works on old posts but not new ones. I suspect this has something to do with the Gutenberg editor as only the new posts have had pictures added via Gutenberg editor.

Here are a couple of examples. This one works (old post):
http://www.greattravels.co.uk/islands/top-three-things-to-do-on-a-kavos-holiday/
If you click on the image, you get a lightbox.
Same for thsi one published in 2017:
http://www.greattravels.co.uk/europe/londons-most-incredible-restaurants/

But not these two (2019):
http://www.greattravels.co.uk/europe/amsterdams-best-hidden-gems/
http://www.greattravels.co.uk/europe/active-holidays-in-sicily/

The strange thing is that Jetpack gallery/lightbox doesn't work either on the new posts but I think this is due to images not being added to a gallery and also not your issue of course.

Regards,
Henri

**Comment by archetyped** [comment]
Hi, a lightbox is not being displayed for the images on the newer posts because the images in those posts are not linked.  Without links, there is nothing for visitors to click on to launch the lightbox.

See SLB's documentation for more details: [Lightbox not working on New Posts?](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts).
