### ISSUE TITLE
SLB only working intermittently 

### ISSUE THREAD

**Issue by g4dbn** [archetyped/simple-lightbox#780]
## Description of Problem
Not sure exactly when this started, but SLB is not working on pages that were OK last week. Only change I am aware of is that my hosting provided upgraded to PHP 7.3 recently.  SLB appears to work sometimes, but I can't reproduce the conditions to make it work. New pages are also affected. I just got it to work once in Preview (screenshot attached)
![Capture](https://user-images.githubusercontent.com/57620013/76253477-b27b2580-6242-11ea-94a3-9eb9edcf854f.JPG)
, but next time I viewed it, was broken again and just opened the media file URL. I have disabled Akismet and UpdraftPlus with no change.  Activating and deactivating SLB has no effect.  Using theme 2014, tried theme 2013, no change.   I have a default .htaccess with nothing other than the two wordpress default lines.
In the source of the broken pages, I see:

data-slb-active="1" data-slb-asset="1484069371" data-slb-internal="0" data-slb-group="1458"

## Details

* URL of Page exhibiting problem: http://g4dbn.uk and specifically http://g4dbn.uk/?p=1458
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): FF and Chrome
* Version of SLB Installed: 2.8.0
* Other plugins installed: Akismet anti-spam, UpdraftPlus backup.

**Comment by archetyped** [comment]
Hi, it looks like the lightbox's layout is not being consistently loaded in the browser.  This may be related to a change to your server's cURL configuration (see [cURL requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support)), or a network issue.

I would recommend contacting your host regarding the cURL configuration (details at above link).

If the issue is related to a network issue, I would recommend checking the logs (error, access, etc.) for your site's server (e.g. Apache, Nginx, etc.), PHP, and WordPress itself for any log message related to retrieving `layout.html` (the lightbox theme's layout file).

Let me know what you find and I would be glad to take another look if necessary.

**Comment by g4dbn** [comment]
Thanks, I've raised a ticket with the hosting provider

**Comment by g4dbn** [comment]
Oh boy, they have reverted my host to PHP5.4 and broken it.  Marvellous. I've told them to put it back to 7.3 and answer the question I asked about cURL instead.

Fatal error: Default value for parameters with a class type hint can only be NULL in /home/g4dbn/FIHE51A6/htdocs/g4dbn/wp-content/plugins/simple-lightbox/includes/class.field_base.php on line 494

**Comment by g4dbn** [comment]
They say cURL access is  definitely enabled as required. PHP7.3 is back on, so I uninstalled SLB and deleted it and reinstalled and it is still not working.  I'll check the logs and see if I can find anything diagnostic.  When I find the fix, I'll report it here in case anyone else has the same issue with their hosting

**Comment by archetyped** [comment]
Thanks for the update.  Just want to also note that many web hosts tend to overlook that cURL needs to be enabled for **local requests**.  This may require the support request to be elevated to someone who understands what that means, which is why contacting your host's support more than once to confirm this detail may be necessary.

**Comment by archetyped** [comment]
Hi, did you find any details from your site's logs or follow up with your hosting company regarding cURL configuration for your site?

Please provide an updated link to a page exhibiting the issue and I would be glad to take another look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
