### ISSUE TITLE
Request: Full URLs of the JS files

### ISSUE THREAD

**Issue by doggerms** [archetyped/simple-lightbox#795]
## Description of feature/request
Hello, i am writing my personal blog and would like to use Lightbox as photo slider box.
Also would like to combine to another plugin (photonic).
The plugin asking me to put the full urls of the js files of Lightbox.
May i know where is information?
![ref](https://user-images.githubusercontent.com/64589749/80707920-58e5f780-8b1d-11ea-8057-5535c5e5e848.png)

## This feature would be used to
My personal blog - http://block09.net

## If you added this feature, I would:
Eat an apple twice tongiht.

**Comment by doggerms** [comment]
problem sloved - thx -

**Comment by archetyped** [comment]
Hi, glad to hear your issue was solved. 

Just for confirmation, SLB functions with Photonic galleries without any modifications as long as Photonic's **"Inbuilt Lightbox libraries"** option is set to **None** so that no other lightbox scripts are loaded on the page.

Adding URLs of SLB's files to Photonic's settings is not necessary.
