### ISSUE TITLE
[Support] Toolset AJAX Filtering

### ISSUE THREAD

**Issue by Guido81** [archetyped/simple-lightbox#797]
## Description of Problem
The lightbox is not working after filtering results.

I am using toolset to show a view with filter results. I can choose to use ajax to filter results or use full page refresh. On filter with ajax the lightbox is not working anymore. On full page refresh it still works. But i really want to use ajax to filter.

I have the option to put in some JS after the results are filtered or execute a function after the results are filtered.

What JS or function can i use after the results are filtered to show the lightbox/make it work again?

To test it out i have the url.

If you click on "Click here to enlarge" underneath an image it will work. If you chosse a filter on the left and then try to enlarge it doesn't work.

Underneath the filters i have pagination. Those are set on full page refresh. You will see if you switch pages the lightbox works. But if i put ajax on the pagination then it will behave like the filter options and the lightbox will not work.

Hope you can help me out! 

Thanks
Guido

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by Guido81** [comment]
https://wordpress-403092-1269364.cloudwaysapps.com/archived-tests/

**Comment by archetyped** [comment]
Hi, it appears that the AJAX filtering modifies the entire page, clearing all SLB-related details for links on the page (rather than simply hiding non-matching items).

As such, a dedicated extension for SLB/Toolset would likely to be required.  This would also be dependent on whether Toolset supports integration with its AJAX functionality.

 Please feel free to [submit a feature request](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support#feature-requests) for an extension with the functionality you are looking for.  Development is prioritized based on demand, so the feature request will allow others to vote for the extension as well.

**Comment by Guido81** [comment]
Hi, I contacted toolset support and this is there answer:

"I installed that plugin but I couldn't get it to work at all, but nevermind, the principal is the same.
The plugin surely is initialised with some line of JS.
You should be able to re-initialise it after an ajax update using the Views custom JS event, the question is simply what JS can be used to initialise the lightbox code on a page.
If you are in contact with the plugin authors it should be trivial for them to tell you that, and with it you should then be able to add the relevant code to your View (and I can help if you have a problem with that).
Can you ask the plugin authors? No integration required, just one line of JS to (re)initialise the lightbox library."

Can you provide me that JS?

Thanks
Guido
On 4-5-2020 22:02:41, Archetyped <notifications@github.com> wrote:
Hi, it appears that the AJAX filtering modifies the entire page, clearing all SLB-related details for links on the page (rather than simply hiding non-matching items).
As such, a dedicated extension for SLB/Toolset would likely to be required. This would also be dependent on whether Toolset supports integration with its AJAX functionality.
Please feel free to submit a feature request [https://github.com/archetyped/simple-lightbox/wiki/Feedback-&amp;-Support#feature-requests] for an extension with the functionality you are looking for. Development is prioritized based on demand, so the feature request will allow others to vote for the extension as well.

**Comment by archetyped** [comment]
SLB uses both server-side and client-side processing to set up the lightbox.  When Toolset's AJAX filtering modifies the page, it removes SLB's server-side configuration.

SLB cannot function properly without this data, regardless of any JS code that is run, which is why an extension that integrates with Toolset's behavior is necessary.
