### ISSUE TITLE
[Support] Mobile issues when script loading modified

### ISSUE THREAD

**Issue by Web-God** [archetyped/simple-lightbox#799]
## Description of Problem
Hello, 
* https://angelus-plongee.com/photos-sous-marines/ (mobile only);
* All browsers
* V 2.8.1
* {Formidable Forms; Akismet; Advanced Database Cleaner; GDPR Cookie Consent; LiteSpeed Cache; Query Monitor; WordPress File Upload; WP TripAdvisor}

I have a tiny issue on mobile the lightbox not show up when I use this filter of defer parsing, in function.php:
```php
/********************/
    if ( is_user_logged_in() ) return $url; 
    if ( FALSE === strpos( $url, '.js' ) ) return $url;
    if ( strpos( $url, 'jquery.js' ) ) return $url;
    return str_replace( ' src', ' defer src', $url );
/*********************/
```

Thanks a lot for this good plugin
Regards

Alvard Sandz

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hello, SLB functioned properly at the link you provided in multiple browsers (both mobile and desktop).  Please clear your browser's cache before loading the page to ensure that the latest version of the page is being loaded.

If you are still experiencing an issue, please specify which platform and browser you are using (including version numbers for both).

Thank you.

**Comment by Web-God** [comment]
Hello
Thanks for your quick answer.
I know SLB is ok now, sorry it's because I remove the filter defer JS on prod.
Don't know if you can check that somewhere else? 
/*
function defer_parsing_of_js( $url ) {
    if ( is_user_logged_in() ) return $url; 
    if ( FALSE === strpos( $url, '.js' ) ) return $url;
    if ( strpos( $url, 'jquery.js' ) ) return $url;
    return str_replace( ' src', ' defer src', $url );
//add_filter( 'script_loader_tag', 'defer_parsing_of_js', 10 );
}
*/
Thanks anyway

**Comment by archetyped** [comment]
Hi, SLB's scripts are loaded in the footer, and so adding `defer` to these scripts has no performance effect (the `defer` attribute defers loading until the page's body has been loaded).

However, while execution order should not be affected by adding `defer` to scripts, it is possible that a particular browser may not be processing/executing scripts properly due to this attribute.

My recommendation would be to limit adding the `defer` attribute to scripts in the page head only. These are the only scripts that can benefit from being deferred, and it will avoid any issues with browsers that have issues with handling deferred scripts.
