### ISSUE TITLE
Lightbox Not Working

### ISSUE THREAD

**Issue by pbhtest** [archetyped/simple-lightbox#814]
## Description of Problem

We have installed and activated the Simple Lightbox and have added a gallery of photographs to the page (noted below). When you click on any of the thumbnails, the lightbox does not display/popup.

## Details

* URL of Page exhibiting problem:  https://www.elenaprice.com/listings/pleasant-valley-road-westwood-ma/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chrome, Edge
* Version of SLB Installed: Version 2.8.1
* Other plugins installed: AddToAny Share Buttons
AgentPress Listings
Classic Editor
Cloudflare
Contact Form 7
Contact Form DB
Genesis eNews Extended
Genesis Simple Edits
Really Simple SSL
Redirection for Contact Form 7
Simple Social Icons
Smush
Sucuri Security - Auditing, Malware Scanner and Hardening
Testimonials Widget
Video Background
WP Google Maps
WP Mail SMTP
WP Staging
WP Super Cache
Yoast SEO

**Comment by archetyped** [comment]
Hi, everything looks good to go with SLB, but some JavaScript from your theme is triggering an error in the browser that is stopping other JS (including SLB's code) from running.

You can view the error in your browser's web developer tools console.  Once this issue is resolved, SLB should be allowed to function normally.

Please post an update if you are still experiencing an issue once the JS error has been resolved and I would be glad to reopen this ticket and take another look.

Thanks.
