### ISSUE TITLE
My plugin don't work good in other site

### ISSUE THREAD

**Issue by buisontruong** [archetyped/simple-lightbox#816]
## Description of Problem
When click the image. The image lightbox appear in the below the end of post
(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: https://maytinh.io/phan-cung-may-tinh-co-ban-gom-11-bo-phan-chinh/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all
* Version of SLB Installed: 
* Other plugins installed: Yoast, lightspeed cache, worrdfence, theme cream magazine, Jetpack, AMP
I use this plugin for two other site. But everything is perfect. You plugin so powerful in both PC and mobile

**Comment by archetyped** [comment]
Hi, SLB appears to functioning properly at the link provided.  The lightbox is displayed in the center of the screen as expected when a link is clicked when tested in multiple browsers.

The behavior you are experiencing may be due to outdated cached data in your browser.  Clearing your site's cache, logging out of your WordPress site, and then clearing your browser's cache is recommended to ensure that you are viewing the latest version of the site.

If you are still experiencing an issue, please provide a screenshot/recording of the issue and an updated link that exhibits the issue and I would be glad to take another look.

Thanks.

**Comment by buisontruong** [comment]
I found that my curent theme make this happen. so i change another and fixed. Thanks for you support a lot.

Your plugin is so kool

Sincerely,

**Comment by archetyped** [comment]
Ah, glad to hear your issue has been resolved :)

**Comment by buisontruong** [comment]
thank you very much
