### ISSUE TITLE
This slideshow requires JavaScript. - Wordpress 5.5

### ISSUE THREAD

**Issue by phjoshua** [archetyped/simple-lightbox#820]
My slideshow galleries are not showing using Simple Lightbox. 

error message: "This slideshow requires JavaScript."

## Details

https://www.thereviewsarein.com/2020/08/17/the-dirty-nil-release-new-single-doom-boy-announce-fuck-art-album/
Chrome (desktop and mobile)
* Version of SLB Installed: 2.8.1
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, it appears that you may be using a different plugin because SLB does not add anything to the page itself, including a message like you provided.  SLB only controls the display of the lightbox.

Here are some [instructions on identifying plugins causing issues](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).  When that error message disappears, the plugin that was most-recently deactivated is likely the one causing the error.
