### ISSUE TITLE
[Feedback]: caption is for ants

### ISSUE THREAD

**Issue by alicia-wp** [archetyped/simple-lightbox#821]
Hello! love the ease of lightbox. however i find the caption not responsive. it's great for mobile but on desktop it's really small! maybe a custom css box?

**Comment by archetyped** [comment]
Hi, as it may be possible for other factors to affect the appearance of the lightbox, can you please provide the following details so that your request can be fully evaluated:

* Screenshot of lightbox: 
* Link to example page with lightbox: 
* Theme used on site (name and link): 
* Other plugins installed:

Thank you.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
