### ISSUE TITLE
[Feedback]: A masterpiece

### ISSUE THREAD

**Issue by ddegner** [archetyped/simple-lightbox#823]
I've been searching for this functionality in JetPack's carousel but you did it with even more elegance than I could imagine.  The key features that you included are:

1) Turn all photos on a page into a slideshow
2) Include captions
3) Fill the screen with the photo

I'm just starting playing around with this but I hope to find a few more features

4) Easy theming
5) Preloading of images

**Comment by archetyped** [comment]
Glad to hear you're enjoying SLB 😄 

Custom themes are simple with just some HTML/CSS.  See SLB's documentation for [more information on creating custom lightbox themes](https://github.com/archetyped/simple-lightbox/wiki/Themes).

**Comment by ddegner** [comment]
Thanks for the info.  I was able to edit the style sheet directly (I’m sure I’ll loose it when I update the plugin).

Unfortunately the https://archetyped.com/know/slb-theme-anatomy/ page makes no sense to me.  I’ve done a fair share of programming in PHP, but the instructions could be more specific about which file I need to edit to add a theme to the theme selector, where should I place the custom theme folder so they don’t get deleted when updating.

It really is a great script.  Elegant is the correct word.  There isn’t any cruft but it is flexible.

**Comment by archetyped** [comment]
Perhaps you missed the paragraph at the start of the tutorial?

> This tutorial covers adding a custom theme as a **WordPress plugin**, but it could also be done **as part of a theme** with a few simple modifications.

Directly below that is a section titled **Follow Along** with a link to download a starter lightbox theme in the form of a WordPress plugin, so everything regarding where to place the code is already taken care of for you.

The plugin-based approach is the most flexible, but if someone wanted to add it to their theme instead, they would be the best person to determine where the respective code should be added so that it is loaded with WordPress depending on how they've set up their theme.

Let me know if there is anything that is still unclear in the theme tutorial, and I would be glad to take a look.
