### ISSUE TITLE
Breaks when port number is specified in the URL #2

### ISSUE THREAD

**Issue by Karionis** [archetyped/simple-lightbox#832]
I confirm the original issue that the plugin is not working when specifying a port like:
http://localhost:8081/
Although JavaScripts are properly loaded and event listener seems to be attached properly.

When using standard port 80 it works.
http://localhost/

fresh installation of WordPress 5.5.1
Simple Lightbox 2.8.1 
Theme Twenty Twenty Version 1.5
no other plugins active

_Originally posted by @Karionis in https://github.com/archetyped/simple-lightbox/issues/400#issuecomment-699975827_

**Comment by archetyped** [comment]
Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by Karionis** [comment]
I'm sorry, I can't give you access - it's a simple local installation via docker container. I have added the compose file:
[docker-compose.yml.txt](https://github.com/archetyped/simple-lightbox/files/5298211/docker-compose.yml.txt)

**Comment by archetyped** [comment]
Thank you, I will look into it.

**Comment by archetyped** [comment]
After testing, it appears that this issue is Docker-specific and due to using mismatched host/container ports.

With the Docker setup you provided, the site's URL will contain port 8081.  SLB uses WordPress' `wp_safe_remote_get()` to retrieve files (such as the theme layout) by their URL.  However, `wp_safe_remote_get()` (and all other server-side commands) are run *inside* the container, so port 8081 doesn't mean anything to Apache (which is listening on port 80 in the container).

As a result, the files cannot be retrieved.

This is occurring in WordPress itself, so any local requests using WordPress' built-in functionality in the example Docker setup will have the same results.  Therefore, further configuration may be required if using non-standard port mapping.

As this specific issue is related to WordPress itself, it is being closed as out of scope for SLB.
