### ISSUE TITLE
Tried everything but plugin does nothing

### ISSUE THREAD

**Issue by Mpanayi** [archetyped/simple-lightbox#839]
## lightbox plugin does not do anything at all

It's probably not an issue with the plugin, but I've tried other lightbox plugins and they all do nothing on my site, the final plugin i tried was this one with the same outcome. Am I missing something here? Do I need to activate it somewhere? 

Its currently installed and activated, I don't need it for products just on posts as I have some charts that need to be seen clearly.

https://emeraldhemps.com/cbd-for-schizophrenia-and-psychosis/
All browser tried on desktop and mobile
Tried other lightboxes but they are now deleted
simple light box  Version 2.8.1
Wordpress version 5.5.3
Theme:  Woodmart Child

**Comment by michael-sfx** [comment]
same here
WP 5.5.3
Plugin: 2.8.1
theme: Twenty Seventeen 2.4

**Comment by archetyped** [comment]
@Mpanayi Hi, there do not appear to be any image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.

@michael-sfx if your page contains valid links and you are still experiencing an issue, please [create a new ticket](https://github.com/archetyped/simple-lightbox/issues/new/choose) so that your issue can be fully evaluated.

Thanks.

**Comment by Mpanayi** [comment]
https://emeraldhemps.com/cbd-for-schizophrenia-and-psychosis/


Here you go , lightbox installed images on post.. nothing happening

**Comment by archetyped** [comment]
@Mpanayi see my previous response.  Your images need to be linked for there to be something for visitors to click on to display a lightbox.
