### ISSUE TITLE
image over 15 pcs will not load completely

### ISSUE THREAD

**Issue by gloriette** [archetyped/simple-lightbox#841]
## Description of Problem

1. image over 15 pcs will not load completely

2.besides, the lighbox image not align in middle but align on top (mobile view) instead. 

kindly assist, tq

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: 
https://www.gloriettetale.com/02-newborn-001/
https://www.gloriettetale.com/02-newborn-003/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.):
chrome 

* Version of SLB Installed: 

* Other plugins installed: 
master slider

**Comment by archetyped** [comment]
Hi, all images in the slider carousels at the links you provided were displayed properly in the lightbox.

Please clear your browser's cache and fully refresh the page to ensure that no outdated data is being used when displaying the page and test again.  If you are still experiencing an issue, please provide a short screen capture video that displays the issue you are experiencing.

Thanks.

**Comment by gloriette** [comment]
[image: image.png]

hi problem still exists, it supposed 16 pages in total, but it shows 7
pages only, i've tested in both mobile and pc same result, after cleared
all caches, tq

**Comment by archetyped** [comment]
Hi, it looks like you meant to include an image, but images need to be added directly to the GitHub ticket, not via email.  Please upload the image and I would be glad to take a closer look.

However, it sounds like you might be referring to navigating through the images directly in the lightbox, not the slider carousel on the page itself.

When the page is first loaded, the lightbox does indeed only show 7 images.  This is because the carousel on the page only loads the first 7 images initially.  When other slides in the carousel are selected, the carousel replaces the 7 initial images with the new ones (usually 7 images, but sometimes more).

SLB displays images from the page itself, so when the carousel removes images from the page, they are no longer available to SLB.

The solution would be for the carousel to include all image links on the page from the start.  This may be possible via a setting in the specific carousel you are using, or a different carousel that provides this functionality may be required.  If you can provide a link to the specific carousel you are using, I would be glad to take a closer look.
