### ISSUE TITLE
Launching slideshow from single link - slideshow issues

### ISSUE THREAD

**Issue by amhead** [archetyped/simple-lightbox#846]
## Description of Problem
Hello - 
I have two separate issues at this moment - I have launched the slideshow from the first section called "the water series" - VIEW WORKS is the link that opens the slideshow lightbox.

1. I launched a slideshow from a single link and have succeeded (yeah!), but the slideshow is showing 12 slides and not just the 6 that wrote in html. It is repeating the slides twice, but I am not sure where it is pulling it's info from.

2. My second issue is that the first slide that is used to launch the slideshow appears twice - first as the way it should - with the correct name (hidden pond) then as slide #7 with the name "VIEW WORKS" - see picture here: https://pasteboard.co/JEW82Qx.jpg - how do I get rid of the "VIEW WORKS" slide?

Here is the code i am using for to trigger the light box: 

```
<h4 style="text-align: center"><a href="https://annemuller.wpengine.com/wp-content/uploads/2020/12/Anne-Muller_-the-Water-Series_Hidden-Pond-2-A.jpg" title="Hidden Pond" > VIEW WORKS</a></h4>
<div style=display:none>

<a href="https://annemuller.wpengine.com/wp-content/uploads/2020/12/Anne-Muller_The-water-series_October-Afternoon-3-A.jpg" Title="October Afternoon"></a>

<a href="https://annemuller.wpengine.com/wp-content/uploads/2020/12/Anne-Muller_the-water-series_reflextion.jpg" title="reflection"></a>

<a href="https://annemuller.wpengine.com/wp-content/uploads/2020/12/Anne-Muller_the-water-Series_The-Creeks-.jpg" title="The Creeks"></a>

<a href="https://annemuller.wpengine.com/wp-content/uploads/2020/12/Anne-Muller_The-water-series_This-Day-.jpg" title="This Day"></a>

<a href="https://annemuller.wpengine.com/wp-content/uploads/2020/12/Anne-Muller_the-water-series_Winter-Sunrise-4-A.jpg" title="Winter Sunrise"></a> </div>
```

## Details

* URL of Page exhibiting problem: http://annemuller.wpengine.com/ 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome and Safari is all I have checked
* Version of SLB Installed: Version 2.8.1 
* Other plugins installed: Contact Form 7, Elementor, Slider Revolution, Photo Gallery (not active), Akismet Anti-Spam (not activated)

Any help would be greatly appreciated! Thanks.

**Comment by archetyped** [comment]
Hi, great job on creating the slideshow.

## Grouping

All images in the lightbox are coming from links on the page.  For example, `Anne-Muller_-the-Water-Series_Hidden-Pond-2-A.jpg` is used for the "View Works" link for the Water Series, and as the "View Post" link for the Gold Series.

If you want to isolate these collections (i.e. Water Series, Gold Series, etc.) from each other, you can group them using the `[slb_group]` shortcode.  See [SLB's Shortcode documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes#slb_group) for more details.

## Lightbox caption

The first link to the above image contains a `title` attribute ("Hidden Pond"), so that is what is used as the caption as per [SLB's title precedence](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence).

The second link to the image does not contain a `title` attribute or any other metadata, so the link's text ("View Post") is used as a fallback (see above documentation for more details).

Setting the `title` attribute for the 2nd link to the image will allow you to control what is displayed as its caption.
