### ISSUE TITLE
No metadata showing

### ISSUE THREAD

**Issue by marc-bail** [archetyped/simple-lightbox#864]
There is no metadata showing with the lightbox.  I'm using many plugins but I removed them all except Elementor pro because I get the issue with an Elementor pro gallery.  In the html code I get the slb_template_tag_title, status and description but they are just empty.  You can find the issue on https://marisoltmp.site/portfolio/livres-jeunesse/pastel/.

Previously I had the same problem on a few of my images but now all of them have no metadata at all.

**Comment by archetyped** [comment]
Was the site migrated to HTTPS after the images were uploaded?  If so, what method was used to migrate to HTTPS?

When the link you provided is loaded via HTTP ([link](http://marisoltmp.site/portfolio/livres-jeunesse/pastel/)), the metadata is displayed lightbox for the images.  This may indicate an incomplete migration to HTTPS, causing WordPress' media library to be unable to find metadata when images are loaded via HTTPS.

Fully migrating to HTTPS requires updating the URLs of uploaded media in WordPress' database.  Most plugins that "switch" a site to HTTPS do not update URLs, so this may be the issue if a plugin is handling the HTTPS migration.

**Comment by marc-bail** [comment]
Thanks for you answer.

I think it migrated to HTTPS after the images were uploaded.  Sorry but I'm really not familiar with the difference between HTTP and HTTPS.  I understand that HTTPS is the secured version but I don't know how to reach that security.  On wordpress I use the "Really Simple SSL" plugin which was not activated  when you looked at the site.  That could explain why I was writing in my first question: "Previously I had the same problem on a few of my images but now all of them have no metadata at all." 

Activating the "Really Simple SSL" plugin I am back to my first situation, that is, once in a while there an image that shows no metadata.

I understand that you work for Simple LIghtbox, not Elementor but I'm risking a question: Do you know how to keep Elementor from showing it's lightbox and only show the "Simple Lightbox"?  So far, I couldn't find anything more intelligent that to let Elementor write the html and use a display: none in my css...  There must be something else.

**Comment by archetyped** [comment]
The first result when searching "elementor disable lightbox" is an Elementor documentation page providing [instructions on disabling its built-in lightbox](https://elementor.com/help/lightbox/).  Do those steps not work for you?

If not, there's not much that can be done from SLB's end, so I would recommend contacting Elementor's support for further details on their lightbox's functionality.

---

As for metadata not showing for some images in SLB's lightbox when the "Really Simple SSL" plugin is activated, please provide the following:

* Link to page containing image link that does not show metadata in lightbox.
    * Indicate which specific image link exhibits an issue.
* Screenshot of image in WordPress' media library showing the metadata that should be displayed.

Thanks.

**Comment by marc-bail** [comment]
Thanks again for your reply.

If I disable the Elementor lightbox in the global settings, Simple lightbox is not called unless I specify that the media file should be called if the image is clicked.  Then both lightboxes are called.

As for the metadata not showing: you can find the problem at the same page: https://marisoltmp.site/portfolio/livres-jeunesse/pastel/.  First 3 images are ok, they're showing the description with  links  but the fourth doesn't show anything even if, as far as I can tell, it contains the same information.  I'm sending 2 files showing this information, one in the Elementor gallery and one from the media library.  Other images show the same problem.
Thanks
![desc_no_show](https://user-images.githubusercontent.com/78713895/107307283-64733100-6a54-11eb-9082-39c0207ab662.jpg)
![media library](https://user-images.githubusercontent.com/78713895/107307285-650bc780-6a54-11eb-92c3-f8a8f29e0e0a.jpg)

**Comment by archetyped** [comment]
Along with Elementor's global lightbox setting, it appears that individual galleries also have a lightbox setting that can override the global setting.  The gallery-specific Lightbox setting also needs to be disabled (or set to "Default") for Elementor's lightbox to be disabled for that gallery.

Here are some things you can try to get metadata to display for images that are having issues:

1. Reupload image - upload the image again, add metadata, and add it to the gallery.  Check if the metadata is displayed for the newly updated image.
2. Set the gallery "Link" option to "Attachment Page" - Open the Elementor gallery's properties and update the "Link" option.  Save the changes to the page, refresh and view the page itself (not in the editor), and test the gallery images to see if metadata is displayed properly.

⚠️ **Important:** Do not enable or disable SSL plugin before or after uploading images, as this may create a mismatch between the image's URL that is displayed in the media library and what is actually being stored in the database.

Please let me know your results after testing the above options.

**Comment by marc-bail** [comment]
Hi, thanks again for the follow up.

Unfortunatly nothing worked.  I am using the Elementor pro gallery because it has the right layout for us but for some funny reasons it doesn't allow me to choose the lightbox.  To go around this problem, for debugging purposes, I used the regular gallery which is much more simple but at least allow me to choose the lightbox.  With this gallery, can choose the default lightbox and now only see the "Simple lightbox".  But the problem is still exactly the same, I don't see the metadata.  In fact what  I don't see is the description with this gallery.  With the pro gallery, both description and title are missing.

So just to be clear, I erased my image, reuploaded it, added the metadata and checked, nothing was there.

When I use the Attachment Page I can see all the informations, title and description.

Do you have any other lead?

**Comment by archetyped** [comment]
> I used the regular gallery which is much more simple but at least allow me to choose the lightbox. With this gallery, can choose the default lightbox and now only see the "Simple lightbox". But the problem is still exactly the same, I don't see the metadata. In fact what I don't see is the description with this gallery. With the pro gallery, both description and title are missing.

Please clarify, when using the standard Elementor gallery, are the results the same as in the pro Elementor gallery (no metadata showing for image), or is some of the metadata displayed, but not all (such as the description)?

> When I use the Attachment Page I can see all the informations, title and description.
> Do you have any other lead?

Since metadata is showing in the lightbox when using the attachment page as the link for gallery images, we at least know that the information is being fetched from the Media Library.  This may indicate that WordPress may be having difficulty with the image's file name.

Here are some steps to determine if this is the case:

1. Rename image file to something simple with no special characters, such as `test.jpg`.
2. Upload renamed image file to WordPress media library.
3. Add newly uploaded image to gallery
4. Change gallery's "Link" setting to "Media File".
4. Save post.
5. Clear browser cache.
6. Reload page.
7. Check to see if meta is displayed for image.

If metadata is still not being displayed for the new image, please provide an updated link and I will take another look.

---

As for Elementor's pro gallery missing lightbox setting, I would recommend contacting the plugin's developer to report the issue so that it can be consistent with the standard gallery.

**Comment by marc-bail** [comment]
Thanks again for your work and sorry to take so much of your time.

>> I used the regular gallery which is much more simple but at least allow me to choose the lightbox. With this gallery, can
>> choose the default lightbox and now only see the "Simple lightbox". But the problem is still exactly the same, I don't see 
>> the metadata. In fact what I don't see is the description with this gallery. With the pro gallery, both description and title 
>> are missing.

> Please clarify, when using the standard Elementor gallery, are the results the same as in the pro Elementor gallery (no 
> metadata showing for image), or is some of the metadata displayed, but not all (such as the description)?

No the results are not exactly the same.  For the basic gallery, the title is shown but not the description and for the pro gallery, nothing is shown.

> Since metadata is showing in the lightbox when using the attachment page as the link for gallery images, we at least know
>  that the information is being fetched from the Media Library. This may indicate that WordPress may be having difficulty with
>  the image's file name.

Just to be precise, the attachment page link lead to... the attachment page by itself and not the attachment page inside a lightbox.

I did all the steps and it is just the same problem.

The page is still at  https://marisoltmp.site/portfolio/livres-jeunesse/pastel/.  The first 2 images are from the basic gallery and the others from the pro gallery.

Thanks

**Comment by archetyped** [comment]
The lightbox should be displayed when clicking on gallery items when the gallery's "Link" setting is set to "Attachment Page".  If the lightbox is not being displayed, it further confirms that there is some kind of disconnect between WordPress and items in the media library.

This can be caused by plugins that dynamically change URLs without accounting for the media library, such as many "one-click" SSL plugins.  Unfortunately, there's not much that can be done about this from SLB's end, as the conflicts caused such plugins can vary.

A true HTTPS migration that does not depend on a plugin is the recommended approach to avoid this any other issues, though I know this can difficult if you're unfamiliar with the process.

Further evaluation of these kind of URL mismatches has been added to SLB's to-do list.  This ticket is being closed for now as the issue appears to be caused by other plugin(s), but it will be reopened/updated when there are any updates.
