### ISSUE TITLE
Lightbox not working for Webp files or Avif files

### ISSUE THREAD

**Issue by nzf4de** [archetyped/simple-lightbox#866]
## Description of Problem

WebP images in wordpress don't lightbox, but rather open up by themselves
Avif image files open up as code, they won't lightbox either

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
AVIF images are not widely-supported by browsers, so if the browser does not support it, it cannot be displayed in a lightbox or otherwise.

See here for more information on [AVIF image browser support](https://caniuse.com/avif).

The following image formats are currently supported: gif, png, jpg, jpeg, jpe, jfif, and jif.

WebP support is planned for a future update.

Thanks.

**Comment by nzf4de** [comment]
WebP support is planned for a future update.  --> Did you have an actual date? Is their a line of code we can change now to get it working until the 'future update?'

Obviously I know what web browsers support AVIF files. We're literally turning 1785 x 1785 pixel images that are 512kb in JPG, into 276kb WebP files, and are stunned that AVIF files are 126kb files.......lossless conversion, the quality is amazing. You might want to keep ahead of the curve with that one, as they're a game changer. 

As for browsers that don't support it, theirs a function to have a fall back if the browser doesn't support these types of files.  Problem solved.
