### ISSUE TITLE
Lightbox stopped working with my Atahualpa theme

### ISSUE THREAD

**Issue by ijancigova** [archetyped/simple-lightbox#876]
Lightbox has been working with my theme - Atahualpa, but then it stopped. The photos now open on a separate page and and I have to click again to enlarge.

If I switch to the default Wordpress theme (all other plugins deactivated), it works, when I switch back to Atahualpa, it does not. So I am assuming there is some conflict with the theme. But there was no update/upgrade of the theme recently, so I don't know what could have caused it.  

The website exhibiting problem is www.jancigovci.com.
I see it in Safari and Firefox
I have SLB 2.8.1
Other plugins (latest versions): Aksimet Antispam, Breadcrumb NavXT, Classic Editor, Collapsing Archives, Easy Add Thumbnail, Google Analytics, My Category Order, NextGEN Gallery, Viper's Video Quicktags Migrator, WordPress Related Posts Thumbnails, WP-DBManager

Thank you for looking into this.

**Comment by archetyped** [comment]
Hi, if the issue has been isolated to the theme, then I would recommend reporting the issue to the theme's developer, as that will be the most direct way to get things working again.

If you can provide a link to the specific theme you are using, I would be glad to take a closer look.

Thanks.

**Comment by ijancigova** [comment]
Thank you for your prompt reply.

I’d greatly appreciate if you would take a look. This is the theme: 
https://wordpress.org/themes/atahualpa/ <https://wordpress.org/themes/atahualpa/>
It’s an older one and I’ve been resisting to switching to something else for quite a while now, because I really like it and it’s been working very well. 
But if I don’t get the light box working, I might have to, because it is really cumbersome with the pictures now :(

Any insights, comments, hints on this issue are very welcome.  
Thanks,
Iva

**Comment by archetyped** [comment]
Hi, SLB has been tested with a default installation of the Atahualpa theme and the lightbox functioned properly.

Unfortunately, none of the theme's options can be customized due to errors from the theme being so out of date, so I am unable to test if compatibility is affected by changing any of the theme's settings.

One option is to reset the theme's settings to their defaults, as that appears to allow SLB to function normally.

Alternatively, I would recommend contacting the theme's developer to update the theme, as a theme that has not been updated in this amount of time may also have other issues (security, accessibility, etc.).

If the developer does not update the theme, switching to an up-to-date theme would be recommended.
