### ISSUE TITLE
Suddenly Simple Lightbox Isn't Working

### ISSUE THREAD

**Issue by outtacontext** [archetyped/simple-lightbox#893]
## Description of Problem
When I first installed Simple Lightbox about a month ago, it worked fine. But now it isn't working. I've reset it. And I've deactivated it and reactivated it. I'm on a Mac using Catalina. I'm using the latest version of WP: 5.8. 

![outtacontext_plugins](https://user-images.githubusercontent.com/263483/127557273-149b586b-a07e-48f0-8563-dd8d8d269bd8.jpg)
 

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: https://outtacontext.com/wp4/ (and all pages on this site)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox (latest version: 90.01), Safari 
* Version of SLB Installed: 2.8.1
* Other plugins installed: See attached screenshot

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

Please provide a link to a specific page that exhibits the problem you are experiencing so that we can be on the same page (literally and figuratively) when evaluating your issue.

Please also include a screenshot of SLB's settings page for reference.

Also, as there appear to be other elements (active theme/plugins) that affect the interaction and loading of pages on your site, you may want to check if any of them are conflicting with SLB.  See [these instructions on identifying theme/plugin conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts) and provide names and links to any theme or plugin conflicts you find so that they can be investigated further.

Thanks.

**Comment by outtacontext** [comment]
Doesn’t this work when you rollover an image? (You said “image links.”)

**Comment by outtacontext** [comment]
Wait a minute, just so I understand this, I should create a link (i.e <a href="https://foobar-image.jpg"><img scr="https://https://foobar-image.jpg"></a>) for the plugin to work? (I tried that with an image and it did work.)

**Comment by archetyped** [comment]
Yes, as noted in the **Usage** section on [Simple Lightbox's plugin description](https://wordpress.org/plugins/simple-lightbox/):

> 1. Insert **links** to images/image attachments into your posts/pages

Also as per my previous reply, links are required for visitors to have something to click on to open the lightbox.  Without a link to the image that should be displayed, there is nothing to launch the lightbox, nor any indication of _what_ should be displayed in the lightbox.

It sounds like SLB is working as intended on image links, so this ticket is being closed.  If you are still experiencing an issue, please provide additional details/links and I would be glad to reopen this ticket and take another look.

Thanks.

**Comment by outtacontext** [comment]
Thanks!!!!

Jeff

 

Yes, as noted in the Usage section on Simple Lightbox's plugin description:
Insert links to images/image attachments into your posts/pages
Also as per my previous reply, links are required for visitors to have something to click on to open the lightbox. Without a link to the image that should be displayed, there is nothing to launch the lightbox, nor any indication of what should be displayed in the lightbox.

It sounds like SLB is working as intended on image links, so this ticket is being closed. If you are still experiencing an issue, please provide additional details/links and I would be glad to reopen this ticket and take another look.

Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
