### ISSUE TITLE
Simple Lightbox does not display title, description like before

### ISSUE THREAD

**Issue by HVECT** [archetyped/simple-lightbox#895]
## Description of Problem

Recent updated Simple Lightbox does not display title or description of the linked image any more. It displays the link text instead.

## Details

* URL of Page exhibiting problem: https://gesneriads.info/genera/calcareoboea-coccinea/
* Browser(s) exhibiting problem: Chrome, Microsoft Edge, Pixel5 phone
* Version of SLB Installed: 2.8.1
* Other plugins installed:

**Comment by Growver** [comment]
Further to the original description of the problem, Simple Lightbox is no longer displaying either Description or Caption text from the image details. It is only displaying the link text. We normally use Description text to produce the caption in the displayed image, not Caption text (normally blank). To check, I added Caption text and it is also not displayed with the image.

This is an important issue for us since photographer credit and copyright information are included in Description text, and is displayed for thousands of images in our large site.

Another example can be seen in this page:  https://gesneriads.info/genera/achimenes-antirrhina/

The first link should display Description text, beginning with:
"Photo by Leslie Brothers, courtesy of the Smithsonian Institution - Grown at the Smithsonian Institution greenhouses". Only the link text is displayed.

**Comment by HVECT** [comment]
Found the problem:  site has moved to https:// but the WP-config file still have constant pointing to http://
The Simple Lightbox works fine after the correction.

**Comment by archetyped** [comment]
Hi, glad to hear you found the actual cause of your issue.

For future reference, all versions of the plugin are on [SLB's Releases page](https://github.com/archetyped/simple-lightbox/releases).  You can install any previous version from here to confirm whether an issue is related to an update to the plugin or not.

**Comment by HVECT** [comment]
Thank you so much. It is a great plugin!!
Hung Nguyen
________________________________
