### ISSUE TITLE
Use with WP Ultimate Grid

### ISSUE THREAD

**Issue by lesbouchard** [archetyped/simple-lightbox#898]
Using Wp Ultimate Grid from Bootstrap Ventures.  According to developer,  JavaScript probably needs to "reload" once the new images are on the page, since Lightbox doesn"t work when new images are loaded.  See at https://procede.ca/gallery/.

He recommends checking with the developer if there's a function that can be called once the new images are loaded.

**Comment by archetyped** [comment]
Hi, the link you provided was not loading, but SLB uses server-side functionality for lightbox content, so new content loaded via AJAX will need to be supported via an extension.

See here for more information: [Add on: AJAX Content Loading](208).

If you would like to see "WP Ultimate Grid" supported, please also be sure to include a link to the plugin so that it can be evaluated when submitting the details at the above post.

Thanks.

**Comment by lesbouchard** [comment]
Plugin can be found at 

https://bootstrapped.ventures/wp-ultimate-post-grid/
