### ISSUE TITLE
The plugin does not work on my site

### ISSUE THREAD

**Issue by soareindustrial** [archetyped/simple-lightbox#920]
## Description of Problem
The plugin does not work on my site
(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details
i have installed and activated the plug in but i does not do anything.
* URL of Page exhibiting problem: https://automatizaribft.ro/foto/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, something appears to be preventing the loading of SLB's JS/CSS files, though it's difficult to determine without any of the requested details being provided.

It may be due to a caching plugin, the JS errors that are triggered when the site loads, or a plugin conflict.  See here for [instructions on identifying plugin/theme conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).

Please post an update here if a plugin conflict is identified, and I would be glad to take another look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the previously-requested details and I would be glad to take another look.

This ticket will be closed in 24 hours due to inactivity

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
