### ISSUE TITLE
Theme Conflict

### ISSUE THREAD

**Issue by chip-** [archetyped/simple-lightbox#928]
## Description of Problem

Simple Lightbox appears to not be working with my theme, aThemes Botiga: https://athemes.com/theme/botiga/

This is a clean WP install with everything current. I have followed the troubleshooting suggestions, and if I switch to the stock Twenty Twenty-One theme it works as expected. I think that rules out a lot of things and narrows it down to the theme. I am reporting this as requested [here](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts). 

## Details

* URL of Page exhibiting problem: https://dunningkrugerfx.com/effects/modulation/chorus/a-weird-amount-of-chorus/ (this is one of several posts with a gallery)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome 97.0.4692.71, Firefox 96.0.1 
* Version of SLB Installed: 2.8.1
* Other plugins installed: several, although the behavior is the same even when all except for SLB are disabled

Thanks!

**Comment by archetyped** [comment]
Thanks for the report. Botiga v1.0.9 has been tested with SLB and no issues were found (images are displayed in the lightbox).

However, the page at the link you provided does have an issue where the page's full HTML is truncated.  This causes code included at the bottom of the HTML (such as SLB's code) not to be loaded for the page.

This may be due to a plugin or the child theme you are using.

## Recommendations

1. Remove and reinstall the latest version of the Botiga theme (currently v1.0.9)
2. Activate the main Botiga theme (not a child theme) - Confirm whether SLB works or not.
3. Activate the child theme - Confirm whether SLB works or not.

* If SLB stops working when the main Botiga theme is active, please provide an updated link, and I would be glad to take another look.
* If SLB stops working when the child them is active, contacting the child theme's developers is recommended.  Unfortunately, nothing can be done from SLB's end, as the child theme's code cannot be evaluated from here.

**Comment by chip-** [comment]
Oh, you're totally right...it's the child theme, which has terrible developer (me). So sorry to bother you. Thanks so much for your prompt response and troubleshooting help.

**Comment by archetyped** [comment]
Glad to hear your issue was resolved :)
