### ISSUE TITLE
lightbox not working on every page

### ISSUE THREAD

**Issue by Mantu2** [archetyped/simple-lightbox#976]
I have a website where the lightbox is working on pages which are just basic pages - no modifications done. However, the were I would like to have lightbox the most is not working. I'm having a gallery which is custom coded just for the purpose. When clicking the picture it just opens as a big picture, not in the lightbox. Since the plugin is working ok in all other parts of the site, the list of other plugins are those which are used in the gallery code.

## Details

* URL of Page exhibiting problem: https://vapaalehdykka.net/accordion-gallery/kuningas-34/?lang=en  (and others
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chromium
* Version of SLB Installed: Versio 2.9.2
* Other plugins installed: Smush Pro, Advanded Custom Fields (Multilingual), Custom, custom post type UI

**Comment by archetyped** [comment]
> I'm having a gallery which is custom coded just for the purpose.

Hi, please provide details on what you mean by "custom coded".

**Comment by Mantu2** [comment]
The gallery code is constructed from various plugins and it is having its own menu in the back end. So there has been used hard coding, too. I cannot say exactly how has it been made since I have not done the coding.

**Comment by archetyped** [comment]
How is the gallery being added to the page/post?  This is significant because...

* If it is hard-coded in the theme template, then you can use the `slb_activate()` template tag for content outside of WordPress' standard content areas ([template tag documentation](https://github.com/archetyped/simple-lightbox/wiki/Activation#manual-activation)).
* If it the page/post is using a custom template, then the template must meet [SLB's theme requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements#theme).
* etc.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by Mantu2** [comment]
Hi,

The issue still exists. Since I've not done the coding in first place, I'll leave the fixing to my coder. She'll have a look to the matter at some point soon. Thanks for you patience.

**Comment by archetyped** [comment]
Thanks for the update. I'm closing this ticket for now, but please feel free to provide an updated link and the previously-requested details, and I would be glad to reopen this ticket and take another look.
