### ISSUE TITLE
キャプションの表示

### ISSUE THREAD

**Issue by NEET-MAN25** [archetyped/simple-lightbox#980]
## Description of Problem

画像のテキストにおいて、2.6.0までは「キャプション」が表示されていましたが、これ以降は「タイトル」が表示されてしまいます。

「設定」において、表示するテキストをの優先順位を「キャプション」と「タイトル」で切り替えられると非常に助かります。

個人的にはキャプションの優先順位を最上位に切り替えたいのです。

キャプションは記事中において個別に設定するものですからやはりその記事においては強調されるものだからです。タイトルはキャプションがない場合に表示されれば十分です。

（私は記事の中の画像ごとにキャプションを設定している為、タイトル表示されてしまうと記事の内容まで変わってしまうのです。こうなるとプラグイン自体使えなくなってしまいます。）

## Details

* URL of Page exhibiting problem: https://murakumo25.com/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: v2.9.3
* Version of  WordPress installed: v6.1.1
*  Version of  theme: AFFINGER6 / STINGERPRO
* Other plugins installed: 

インストールされているその他のプラグイン

AddQuicktag
**Advanced Editor Tools (旧名 TinyMCE Advanced)　※v4.5.6**
Akismet Anti-Spam 
AmazonJS
Auto Featured Image(Auto Post Thumbnail)
Autoptimize
BackWPup
Better Delete Revision
Broken Link Checker
Classic Editor
Classic WidgetS
Contact Form 7
EWWW Image Optimizer
Google XML Sitemaps
Jetpack by WordPress.com
Login LockDown
Meta Slider
Movable Type・TypePad インポートツール
PS Auto Sitemap
Search Regex
Shortcodes Ultimate
**Simple Lightbox　※v2.6.0　oa　v2.9.3**　
Speech bubble
WebSub (FKA. PubSubHubbub)
WP Multibyte Patch
WP-Appbox
WPアソシエイトポストR2
Widget Logic

（バージョンはすべて最新）

**Comment by archetyped** [comment]
Hi, the priority of content used as the lightbox's title has not changed between v2.6.0 and the current version (v2.9.3).  The order of potential values that may be used as the lightbox's title is still as outlined in [SLB's documentation on title precendence](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence).

As per the documentation, only a manually-set `title` attribute supercedes a custom caption in priority.  As that usually requires the link HTML to be manually edited, the `title` attribute is rarely used.

If you are seeing different behavior, please update your original post to include the missing details needed to fully evaluate your issue, and I would be glad to take a look.

**Comment by NEET-MAN25** [comment]
丁寧なご返信ありがとうございます！

[タイトルの優先順位に関する SLB のドキュメント](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence)は理解しておりますが、

v2.6.0とv2.9.3では表示される内容が異なるのです。

![bandicam 2022-12-15 14-49-27-319](https://user-images.githubusercontent.com/120386224/207782876-d40990ef-b8eb-4aed-884e-964efae7ae38.jpg)

v2.6.0では、「記事中の画像編集におけるキャプション」が最優先で表示されています。

![bandicam 2022-12-15 14-47-45-679](https://user-images.githubusercontent.com/120386224/207782908-5aac34d4-5a2d-4589-b145-518cd65341cf.jpg)

v2.9.3では「メディアライブラリのタイトル」が最優先で表示されます。（v2.6.0では、上記の条件のキャプションが存在しない場合に表示されていました）

その他の条件はすべて同じです。（プラグイン、テーマ、WordPressのバージョン、PHPのバージョン、サーバー）

**Comment by NEET-MAN25** [comment]
_※加えて、これはテーマ側の問題だと思いますが（AFFINGER6）、**「v2.6.0では、記事の中の画像の数が多いと、機能しない」**というエラーが発生します。ただし前のテーマでは起きないエラーです（STINGER PRO）。v2.9.3にすればOKです。しかしそうすると今度はキャプションが表示されないので困っています。_

**Comment by NEET-MAN25** [comment]
メディアライブラリのタイトルは手動で設定しなくとも、

**「メディアライブラリに画像をアップロードした時点で、画像の名称がそのまま使用される」**ので、

v2.6.0のときもv2.9.3のときも同じ設定でした。

![bandicam 2022-12-15 14-23-01-512](https://user-images.githubusercontent.com/120386224/207785930-4dc72b61-7129-4b95-9f0c-39dd387c61a5.jpg)

_※「手動で設定されtitleた属性」とは、記事の中の画像編集における上級者設定で行うものではないですよね？_

**Comment by NEET-MAN25** [comment]
※ちなみに使用しているのは「ClassicEditor」です。ブロックエディタは使用していません。

**Comment by NEET-MAN25** [comment]
v2.9.3にて、メディアライブラリのタイトルを消してみましたら、何も表示されませんでした。

これは「キャプション自体が表示されていない」ということになります。

![bandicam 2022-12-15 16-57-26-534](https://user-images.githubusercontent.com/120386224/207804731-59c305ec-bcb1-45fa-8496-70ec51a8938d.jpg)
![bandicam 2022-12-15 16-56-36-343](https://user-images.githubusercontent.com/120386224/207804750-65f18bdd-aaed-40ac-bc34-b92759a3847a.jpg)

**Comment by NEET-MAN25** [comment]
**テーマを変更してみたら機能しました！？**

![bandicam 2022-12-15 17-07-28-583](https://user-images.githubusercontent.com/120386224/207806566-06e92ded-188c-4bce-b25d-57bbddd85561.jpg)

**どうやらテーマの方に問題があるみたいです。**

キャプション情報の取得を邪魔しているのですかね。

ご対応させてしまい申し訳ありません！

**Comment by NEET-MAN25** [comment]
**_**※テーマを複数変更して試しましたが、キャプション表示されるものとされないものが複数あります**_**

**Comment by NEET-MAN25** [comment]
また別のブログですが、

**そこではタイトルも表示されません。今度は「記事内で画像編集した代替テキスト」が表示されます。**

![bandicam 2022-12-15 18-00-34-914](https://user-images.githubusercontent.com/120386224/207817293-79228daa-d354-41c8-82a9-454bd1d3cc43.jpg)

https://this-is-rpg.com/

![bandicam 2022-12-15 17-58-16-183](https://user-images.githubusercontent.com/120386224/207817347-c6082ff9-25da-4749-9b77-d71266280476.jpg)

https://this-is-rpg.com/simulation-rpg/9540/

こちらのブログはv2.9.3を使用しておりますので、よろしければご検証などにお使いください。

**Comment by archetyped** [comment]
Thank you for the additional details.

## Manually-set `title` attribute

The `title` attribute I referred to is set on the *link* (not the image).  There is no form field for it in WordPress' media editor, so it is generally only present when the HTML code is manually edited.

For example:

```html
<a href="image.png" title="Manually-set title">...</a>
```

## Theme compatibility

SLB currently supports modern standards-compliant themes that [support HTML5 markup](https://developer.wordpress.org/reference/functions/add_theme_support/#html5).  Evaluating support for legacy themes is on the to-do list, but it is not a high priority as old/outdated themes also have other issues to deal with (security, bugs, browser compatibility, etc.).

Adding the following to the theme's `functions.php` file will enable caption support by SLB, but it may also result in unexpected behavior with legacy themes:

```php
add_theme_support( 'html5', array( 'gallery', 'caption' ) );
```

This is one of the reasons that the theme used on https://this-is-rpg.com/simulation-rpg/9540/ shows the "Alternative Text" value in the lightbox rather than the caption.  The theme is rendering the caption on the page using a legacy method, which SLB does not support.

## CDN

The other reason that the caption is not shown in the lightbox on this-is-rpg.com is because the image links are being rewritten to point to a CDN (appears to be Jetpack's CDN on this site).

Some CDN providers (such as Jetpack) modify the image link URLs before other plugins can process the links in the post, preventing the retrieval of the caption/title metadata from the site's media library.  You can confirm this by temporarily disabling the CDN functionality on the site, clearing all caches, and testing the links again to see if the captions are properly displayed.

Support for such CDN providers would [require an extension](https://github.com/archetyped/simple-lightbox/issues/33).

## Summary

In summary, the keys for full compatibility with SLB are:

* Use modern/standards-compliant themes.
* Avoid conflicts caused by other plugins.

You can narrow down the specific causes of any issues by following these [instructions on troubleshooting plugin/theme conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).

You can [report any plugin/theme conflicts](https://github.com/archetyped/simple-lightbox/wiki/Reporting-Issues) you find and I will see what can be done from SLB's end to resolve them.

**Comment by NEET-MAN25** [comment]
ご返信とご対応に感謝します！

`functions.php`に

`add_theme_support( 'html5', array( 'gallery', 'caption' ) );`

と追加したところ正常に機能しました！

**Comment by NEET-MAN25** [comment]
このプラグインは性能も対応も素晴らしいですね！

**本当にありがとうございました！

これからも使い続けます！**

できればPayPalで寄付を募ってください！

**Comment by archetyped** [comment]
Glad to hear your issue was resolved!  🤙🏽
