### ISSUE TITLE
Close X not working on Android Galaxy S20

### ISSUE THREAD

**Issue by tplowe56** [archetyped/simple-lightbox#996]
Close X not working on Android Galaxy S20

The Close X not working on Android Galaxy S20. I have to click outside the image to get the image to close.

## Details

* URL of Page exhibiting problem: https://www.loweprofile.com/investing101/backtesting/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  Does not work on  Android, works on IOS and Windows. Exhibits same behavior on Chrome development node in Windows.
* Version of SLB Installed:  Latest
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please provide the following details so that your issue can be fully evaluated:

* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  
    * 📒 **Note:** "Android" is an operating system, not a browser.  Please specify the name and version of the browser you are using so that your issue can be replicated.
* Version of SLB Installed: 
    * 📒 **Note:** "Latest" is not a valid version. Version information of all plugins is listed on your site's **Plugins** admin page.
* Other plugins installed:

**Comment by tplowe56** [comment]
Here is the information as requested:

https://www.loweprofile.com/investing101/


Simple Lightbox - Version 2.9.3
Operating system Android 13; SM-G781W Build/TP1A.220624.014
Application version Chrome 110.0.5481.65

Other plugins installed:

Easy Google Fonts
Gutenberg
Media Library Folders
Post Type Switcher
Read More Pro
Stockdio Historical Chart
UpdraftPlus - Backup/Restore
WPCode Lite
WPFront Scroll Top


Sincerely,

Thomas Lowe
3070 North Shore Dr,
Wayzata, MN 55391
(612) 963-3919

**Comment by archetyped** [comment]
Thanks.  The provided links have been tested on multiple Android/iOS devices and SLB's close button functioned properly in all tested browsers, including Chrome 110.0.5481.65.

It may be possible that you are viewing a stale cached version of the site on your device/browser.  [Clearing the browser's cache](https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform=Android) and refreshing the page is recommended to ensure that the page's current code is downloaded.

If you are still experiencing an issue after clearing the cache, testing in a different browser (e.g. [Firefox](https://www.mozilla.org/en-US/firefox/browsers/mobile/android/), etc.) is recommended to help isolate the cause of the issue.

For example, if the lightbox's close button works in a different browser, then the issue is with your Chrome installation.  Fully uninstalling and reinstalling Chrome may resolve your issue.  Restarting the device after uninstalling Chrome may also be a good idea.

However, if the issue also occurs in a different browser, then the issue may be related to your specific device.  Testing the site on a different device is recommended to confirm this.

Please let me know what you find, and I would be glad to take another look if there are additional details to test.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
